/**
 * Phase C — Content Manifest Interface (C1)
 * 
 * Single source of truth for all pages generated by Content OS.
 * v1.0.0 - Frozen
 */

import { z } from 'zod';

// Schema for content manifest validation
export const ContentManifestSchema = z.object({
  // Core identifiers
  id: z.string().uuid(),
  slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
  type: z.enum([
    'agent',
    'category',
    'comparison',
    'research',
    'mcp_server',
    'pillar',
    'governance',
    'pricing'
  ]),

  // Routing
  path: z.string().startsWith('/'),
  canonicalPath: z.string().startsWith('/'),

  // Content
  title: z.string().min(1),
  description: z.string().min(1),
  summary: z.string().optional(),
  content: z.string().optional(),

  // Entity relationship
  entityId: z.string().optional(),
  entityType: z.enum([
    'agent',
    'category',
    'comparison',
    'research',
    'mcp_server',
    'author'
  ]).optional(),

  // SEO
  priority: z.number().min(0).max(1).optional(),
  changeFrequency: z.enum([
    'always', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'never'
  ]).optional(),

  // Metadata
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  publishedAt: z.string().datetime().optional(),
  contentType: z.string().optional(),

  // Quality
  qualityScore: z.number().min(0).max(100).optional(),
  evidenceScore: z.number().min(0).max(100).optional(),

  // State
  status: z.enum([
    'draft',
    'in_review',
    'published',
    'archived',
    'needs_update'
  ]).default('draft'),

  // Relationships
  relatedEntities: z.array(z.string()).optional(),
  redirectFrom: z.array(z.string()).optional(),

  // Versioning
  version: z.string().regex(/^\d+\.\d+\.\d+$/),
  schemaVersion: z.string().default('1.0.0')
});

export type ContentManifest = z.infer<typeof ContentManifestSchema>;

/**
 * ManifestRepository - Stores and manages content manifests
 */
export class ManifestRepository {
  private manifests: Map<string, ContentManifest> = new Map();
  private bySlug: Map<string, ContentManifest> = new Map();
  private byPath: Map<string, ContentManifest> = new Map();

  /**
   * Add a manifest to the repository
   */
  add(manifest: ContentManifest): void {
    this.manifests.set(manifest.id, manifest);
    this.bySlug.set(manifest.slug, manifest);
    this.byPath.set(manifest.path, manifest);

    // Handle redirects
    if (manifest.redirectFrom) {
      for (const from of manifest.redirectFrom) {
        this.byPath.set(from, manifest);
      }
    }
  }

  /**
   * Find manifest by ID
   */
  findById(id: string): ContentManifest | undefined {
    return this.manifests.get(id);
  }

  /**
   * Find manifest by slug
   */
  findBySlug(slug: string): ContentManifest | undefined {
    return this.bySlug.get(slug);
  }

  /**
   * Find manifest by path
   */
  findByPath(path: string): ContentManifest | undefined {
    return this.byPath.get(path);
  }

  /**
   * Get all manifests of a specific type
   */
  getByType(type: ContentManifest['type']): ContentManifest[] {
    return Array.from(this.manifests.values()).filter(m => m.type === type);
  }

  /**
   * Get all manifests
   */
  getAll(): ContentManifest[] {
    return Array.from(this.manifests.values());
  }

  /**
   * Validate a manifest against the schema
   */
  validate(manifest: unknown): ContentManifest {
    return ContentManifestSchema.parse(manifest);
  }

  /**
   * Check if a manifest exists
   */
  exists(id: string): boolean {
    return this.manifests.has(id);
  }

  /**
   * Get statistics about the repository
   */
  getStats(): {
    total: number;
    byType: Record<string, number>;
    byStatus: Record<string, number>;
  } {
    const byType: Record<string, number> = {};
    const byStatus: Record<string, number> = {};

    for (const manifest of this.manifests.values()) {
      byType[manifest.type] = (byType[manifest.type] || 0) + 1;
      byStatus[manifest.status] = (byStatus[manifest.status] || 0) + 1;
    }

    return {
      total: this.manifests.size,
      byType,
      byStatus
    };
  }
}

// Singleton instance
export const manifestRegistry = new ManifestRepository();