/**
 * ATLAS W0 — Canonical Content Registry (overlay over immutable CSV).
 *
 * The inventory CSV at /tmp/zip_contents/bestaiagent-50-pillar-inventory.csv
 * (50 pillars + 2,500 clusters = 2,550 records) is treated as immutable intake.
 *
 * This registry is the canonical, typed, lifecycle-tracked, evidence-classified
 * projection of that inventory. Source-of-truth for:
 *   - canonicalSlug decisions (P37 / P42 / P44 / P46 defect resolution)
 *   - lifecycle state (candidate, intent_validated, evidence_ready, ...)
 *   - publicationEligible
 *   - redirectFrom
 *   - primaryEntityIds
 *   - relatedEntityIds
 *   - requiredEvidenceClass
 *   - contentFingerprint
 *   - lastReviewed
 *
 * Rules enforced:
 *   - No record is automatically indexable; lifecycle gates required.
 *   - Template-derived pages default to quarantined_template.
 *   - Unknown slugs return 404 — never synthesized.
 *   - Reverse comparison routes 301 to canonical direction.
 *
 * Implemented as a build-time typed object so the registry can be unit-tested
 * and shipped into the routeResolver without runtime CSV parsing.
 */

import { ContentGroup, PageClass, SearchIntent, LifecycleStatus, EvidenceClass, ContentRecord } from './content-registry.js';
import { DRAFTED_CLUSTER_OVERLAY } from './drafted-overlay.js';

const TRUST_PREFIX = '/trust';
const METHODOLOGY_PREFIX = '/methodology';

export const CONTENT_REGISTRY: ContentRecord[] = [
  // ---------------------------------------------------------------
  // WAVE 0 — TRUST / METHODOLOGY FOUNDATION
  // Pages every commercial page depends on. Lifecycle: approved → published.
  // ---------------------------------------------------------------
  {
    inventoryId: 'w0-editorial-methodology',
    group: 'core',
    pillarId: 'W0',
    pageClass: 'methodology',
    searchIntent: 'informational',
    originalSlug: 'editorial-methodology',
    canonicalSlug: 'editorial-methodology',
    canonicalUrl: `${TRUST_PREFIX}/editorial-methodology`,
    parentPillarSlug: null,
    lifecycleStatus: 'approved',
    publicationEligible: true,
    redirectFrom: [],
    primaryEntityIds: [],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'w0-evidence-methodology',
    group: 'core',
    pillarId: 'W0',
    pageClass: 'methodology',
    searchIntent: 'informational',
    originalSlug: 'evidence-methodology',
    canonicalSlug: 'evidence-methodology',
    canonicalUrl: `${TRUST_PREFIX}/evidence-methodology`,
    parentPillarSlug: null,
    lifecycleStatus: 'approved',
    publicationEligible: true,
    redirectFrom: [],
    primaryEntityIds: [],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'w0-rating-methodology',
    group: 'core',
    pillarId: 'W0',
    pageClass: 'methodology',
    searchIntent: 'informational',
    originalSlug: 'rating-methodology',
    canonicalSlug: 'rating-methodology',
    canonicalUrl: `${TRUST_PREFIX}/rating-methodology`,
    parentPillarSlug: null,
    lifecycleStatus: 'approved',
    publicationEligible: true,
    redirectFrom: [],
    primaryEntityIds: [],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'w0-comparison-methodology',
    group: 'core',
    pillarId: 'W0',
    pageClass: 'methodology',
    searchIntent: 'informational',
    originalSlug: 'comparison-methodology',
    canonicalSlug: 'comparison-methodology',
    canonicalUrl: `${TRUST_PREFIX}/comparison-methodology`,
    parentPillarSlug: null,
    lifecycleStatus: 'approved',
    publicationEligible: true,
    redirectFrom: [],
    primaryEntityIds: [],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'w0-corrections',
    group: 'core',
    pillarId: 'W0',
    pageClass: 'methodology',
    searchIntent: 'informational',
    originalSlug: 'corrections',
    canonicalSlug: 'corrections',
    canonicalUrl: `${TRUST_PREFIX}/corrections`,
    parentPillarSlug: null,
    lifecycleStatus: 'approved',
    publicationEligible: true,
    redirectFrom: [],
    primaryEntityIds: [],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'w0-source-classification',
    group: 'core',
    pillarId: 'W0',
    pageClass: 'methodology',
    searchIntent: 'informational',
    originalSlug: 'source-classification',
    canonicalSlug: 'source-classification',
    canonicalUrl: `${TRUST_PREFIX}/source-classification`,
    parentPillarSlug: null,
    lifecycleStatus: 'approved',
    publicationEligible: true,
    redirectFrom: [],
    primaryEntityIds: [],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'w0-affiliate-disclosure',
    group: 'core',
    pillarId: 'W0',
    pageClass: 'methodology',
    searchIntent: 'informational',
    originalSlug: 'affiliate-disclosure',
    canonicalSlug: 'affiliate-disclosure',
    canonicalUrl: `${TRUST_PREFIX}/affiliate-disclosure`,
    parentPillarSlug: null,
    lifecycleStatus: 'approved',
    publicationEligible: true,
    redirectFrom: [],
    primaryEntityIds: [],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'w0-author-reviewer-policy',
    group: 'core',
    pillarId: 'W0',
    pageClass: 'methodology',
    searchIntent: 'informational',
    originalSlug: 'author-reviewer-policy',
    canonicalSlug: 'author-reviewer-policy',
    canonicalUrl: `${TRUST_PREFIX}/author-reviewer-policy`,
    parentPillarSlug: null,
    lifecycleStatus: 'approved',
    publicationEligible: true,
    redirectFrom: [],
    primaryEntityIds: [],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'w0-privacy-dpdp-editorial',
    group: 'india',
    pillarId: 'W0',
    pageClass: 'methodology',
    searchIntent: 'informational',
    originalSlug: 'privacy-dpdp-editorial-policy',
    canonicalSlug: 'privacy-dpdp-editorial-policy',
    canonicalUrl: `${TRUST_PREFIX}/privacy-dpdp-editorial-policy`,
    parentPillarSlug: null,
    lifecycleStatus: 'approved',
    publicationEligible: true,
    redirectFrom: [],
    primaryEntityIds: [],
    relatedEntityIds: [],
    requiredEvidenceClass: 'CRITICAL',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'w0-freshness-policy',
    group: 'core',
    pillarId: 'W0',
    pageClass: 'methodology',
    searchIntent: 'informational',
    originalSlug: 'freshness-policy',
    canonicalSlug: 'freshness-policy',
    canonicalUrl: `${TRUST_PREFIX}/freshness-policy`,
    parentPillarSlug: null,
    lifecycleStatus: 'approved',
    publicationEligible: true,
    redirectFrom: [],
    primaryEntityIds: [],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    lastReviewed: '2026-08-22',
  },

  // ---------------------------------------------------------------
  // WAVE 1 — PILLAR 01 (AI Agents Core & Definitions)
  // ---------------------------------------------------------------
  {
    inventoryId: 'p01-pillar',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'pillar',
    searchIntent: 'informational',
    originalSlug: 'ai-agents',
    canonicalSlug: 'ai-agents',
    canonicalUrl: '/ai-agents',
    parentPillarSlug: null,
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: ['/what-are-ai-agents', '/ai-agent-definition'],
    primaryEntityIds: ['concept:ai-agent', 'concept:agentic-workflow'],
    relatedEntityIds: ['concept:mcp', 'concept:tool-calling', 'concept:orchestration'],
    requiredEvidenceClass: 'STANDARD',
    lastReviewed: '2026-08-22',
  },
  // P01 Cluster subset (highest-value, evidence-ready first wave)
  {
    inventoryId: 'p01-c01',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-for-startups',
    canonicalSlug: 'ai-agents-for-startups',
    canonicalUrl: '/ai-agents-for-startups',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['persona:startup'],
    relatedEntityIds: ['agent:cursor', 'agent:claude', 'agent:vapi'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'build_now',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c02',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'agentic-workflows',
    canonicalSlug: 'agentic-workflows',
    canonicalUrl: '/agentic-workflows',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: ['/agentic-workflow'],
    primaryEntityIds: ['concept:agentic-workflow'],
    relatedEntityIds: ['concept:orchestration', 'concept:multi-agent'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'build_now',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c03',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-vs-chatbots',
    canonicalSlug: 'ai-agents-vs-chatbots',
    canonicalUrl: '/ai-agents-vs-chatbots',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:ai-agent', 'concept:chatbot'],
    relatedEntityIds: [],
    requiredEvidenceClass: 'COMPARISON',
    clusterDisposition: 'build_now',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c04',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-for-solopreneurs',
    canonicalSlug: 'ai-agents-for-solopreneurs',
    canonicalUrl: '/ai-agents-for-solopreneurs',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['persona:solopreneur'],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c05',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-for-freelancers',
    canonicalSlug: 'ai-agents-for-freelancers',
    canonicalUrl: '/ai-agents-for-freelancers',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['persona:freelancer'],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c06',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-for-students',
    canonicalSlug: 'ai-agents-for-students',
    canonicalUrl: '/ai-agents-for-students',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['persona:student'],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c07',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-for-developers',
    canonicalSlug: 'ai-agents-for-developers',
    canonicalUrl: '/ai-agents-for-developers',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['persona:developer'],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c08',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-for-agencies',
    canonicalSlug: 'ai-agents-for-agencies',
    canonicalUrl: '/ai-agents-for-agencies',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['persona:agency'],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c09',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-for-consultants',
    canonicalSlug: 'ai-agents-for-consultants',
    canonicalUrl: '/ai-agents-for-consultants',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['persona:consultant'],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c10',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-for-nonprofits',
    canonicalSlug: 'ai-agents-for-nonprofits',
    canonicalUrl: '/ai-agents-for-nonprofits',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['persona:nonprofit'],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c11',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-for-ctos',
    canonicalSlug: 'ai-agents-for-ctos',
    canonicalUrl: '/ai-agents-for-ctos',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['persona:cto'],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c12',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-for-founders',
    canonicalSlug: 'ai-agents-for-founders',
    canonicalUrl: '/ai-agents-for-founders',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: ['ai-agents-for-startups'],
    primaryEntityIds: ['persona:founder'],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'merge_redirect',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c13',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-automation',
    canonicalSlug: 'ai-agents-automation',
    canonicalUrl: '/ai-agents-automation',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:automation'],
    relatedEntityIds: ['concept:workflow', 'concept:orchestration'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c14',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-workflow',
    canonicalSlug: 'ai-agents-workflow',
    canonicalUrl: '/ai-agents-workflow',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: ['agentic-workflows'],
    primaryEntityIds: ['concept:workflow'],
    relatedEntityIds: ['concept:orchestration', 'concept:automation'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'merge_redirect',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c15',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-lead-generation',
    canonicalSlug: 'ai-agents-lead-generation',
    canonicalUrl: '/ai-agents-lead-generation',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:lead-generation'],
    relatedEntityIds: ['concept:sales', 'concept:marketing'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c16',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-data-analysis',
    canonicalSlug: 'ai-agents-data-analysis',
    canonicalUrl: '/ai-agents-data-analysis',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:data-analysis'],
    relatedEntityIds: ['concept:reporting', 'concept:forecasting'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c17',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-reporting',
    canonicalSlug: 'ai-agents-reporting',
    canonicalUrl: '/ai-agents-reporting',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:reporting'],
    relatedEntityIds: ['concept:data-analysis', 'concept:forecasting'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c18',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-scheduling',
    canonicalSlug: 'ai-agents-scheduling',
    canonicalUrl: '/ai-agents-scheduling',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:scheduling'],
    relatedEntityIds: ['concept:calendar', 'concept:appointments'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c19',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-onboarding',
    canonicalSlug: 'ai-agents-onboarding',
    canonicalUrl: '/ai-agents-onboarding',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:onboarding'],
    relatedEntityIds: ['concept:training', 'concept:implementation'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c20',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-forecasting',
    canonicalSlug: 'ai-agents-forecasting',
    canonicalUrl: '/ai-agents-forecasting',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:forecasting'],
    relatedEntityIds: ['concept:prediction', 'concept:trend-analysis'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c21',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-compliance',
    canonicalSlug: 'ai-agents-compliance',
    canonicalUrl: '/ai-agents-compliance',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:compliance'],
    relatedEntityIds: ['concept:regulation', 'concept:legal'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c22',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-research',
    canonicalSlug: 'ai-agents-research',
    canonicalUrl: '/ai-agents-research',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:research'],
    relatedEntityIds: ['concept:innovation', 'concept:experimentation'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c23',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-content-creation',
    canonicalSlug: 'ai-agents-content-creation',
    canonicalUrl: '/ai-agents-content-creation',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:content-creation'],
    relatedEntityIds: ['concept:copywriting', 'concept:marketing-content'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c24',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-translation',
    canonicalSlug: 'ai-agents-translation',
    canonicalUrl: '/ai-agents-translation',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:translation'],
    relatedEntityIds: ['concept:localization', 'concept:interpretation'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c25',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-fraud-detection',
    canonicalSlug: 'ai-agents-fraud-detection',
    canonicalUrl: '/ai-agents-fraud-detection',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:fraud-detection'],
    relatedEntityIds: ['concept:security', 'concept:risk-assessment'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c26',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-risk-management',
    canonicalSlug: 'ai-agents-risk-management',
    canonicalUrl: '/ai-agents-risk-management',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:risk-management'],
    relatedEntityIds: ['concept:risk-assessment', 'concept:mitigation'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c27',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-personalization',
    canonicalSlug: 'ai-agents-personalization',
    canonicalUrl: '/ai-agents-personalization',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:personalization'],
    relatedEntityIds: ['concept:customization', 'concept:recommendation'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c28',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-documentation',
    canonicalSlug: 'ai-agents-documentation',
    canonicalUrl: '/ai-agents-documentation',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:documentation'],
    relatedEntityIds: ['concept:knowledge-base', 'concept:help-center'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c29',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-invoicing',
    canonicalSlug: 'ai-agents-invoicing',
    canonicalUrl: '/ai-agents-invoicing',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:invoicing'],
    relatedEntityIds: ['concept:billing', 'concept:payments'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c30',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-ticketing',
    canonicalSlug: 'ai-agents-ticketing',
    canonicalUrl: '/ai-agents-ticketing',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:ticketing'],
    relatedEntityIds: ['concept:support', 'concept:issue-tracking'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c31',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-auditing',
    canonicalSlug: 'ai-agents-auditing',
    canonicalUrl: '/ai-agents-auditing',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:auditing'],
    relatedEntityIds: ['concept:compliance', 'concept:review'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c32',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-monitoring',
    canonicalSlug: 'ai-agents-monitoring',
    canonicalUrl: '/ai-agents-monitoring',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['concept:monitoring'],
    relatedEntityIds: ['concept:observability', 'concept:logging'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'needs_more_research',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c33',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'what-is-an-ai-agent-ai-agents',
    canonicalSlug: 'what-is-an-ai-agent-ai-agents',
    canonicalUrl: '/what-is-an-ai-agent-ai-agents',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: ['ai-agents'],
    primaryEntityIds: ['concept:ai-agent'],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'merge_redirect',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c34',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'how-does-an-ai-agent-ai-agents',
    canonicalSlug: 'how-does-an-ai-agent-ai-agents',
    canonicalUrl: '/how-does-an-ai-agent-ai-agents',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: ['ai-agents'],
    primaryEntityIds: ['concept:ai-agent'],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'merge_redirect',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c35',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'why-use-an-ai-agent-ai-agents',
    canonicalSlug: 'why-use-an-ai-agent-ai-agents',
    canonicalUrl: '/why-use-an-ai-agent-ai-agents',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: ['ai-agents'],
    primaryEntityIds: ['concept:ai-agent'],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'merge_redirect',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c36',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'is-an-ai-agent-ai-agents',
    canonicalSlug: 'is-an-ai-agent-ai-agents',
    canonicalUrl: '/is-an-ai-agent-ai-agents',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: ['ai-agents'],
    primaryEntityIds: ['concept:ai-agent'],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'merge_redirect',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c37',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'can-an-ai-agent-ai-agents',
    canonicalSlug: 'can-an-ai-agent-ai-agents',
    canonicalUrl: '/can-an-ai-agent-ai-agents',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: ['ai-agents'],
    primaryEntityIds: ['concept:ai-agent'],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'merge_redirect',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c38',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'should-you-use-an-ai-agent-ai-agents',
    canonicalSlug: 'should-you-use-an-ai-agent-ai-agents',
    canonicalUrl: '/should-you-use-an-ai-agent-ai-agents',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: ['ai-agents-vs-chatbots'],
    primaryEntityIds: ['concept:ai-agent', 'concept:chatbot'],
    relatedEntityIds: [],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'merge_redirect',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c39',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'how-to-choose-an-ai-agent-ai-agents',
    canonicalSlug: 'how-to-choose-an-ai-agent-ai-agents',
    canonicalUrl: '/how-to-choose-an-ai-agent-ai-agents',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: ['ai-agent-evaluation'],
    primaryEntityIds: ['concept:ai-agent'],
    relatedEntityIds: ['concept:evaluation', 'concept:selection-criteria'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'merge_redirect',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c40',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'how-secure-is-an-ai-agent-ai-agents',
    canonicalSlug: 'how-secure-is-an-ai-agent-ai-agents',
    canonicalUrl: '/how-secure-is-an-ai-agent-ai-agents',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: ['ai-agent-evaluation'],
    primaryEntityIds: ['concept:ai-agent', 'concept:security'],
    relatedEntityIds: ['concept:security-assessment', 'concept:vulnerability'],
    requiredEvidenceClass: 'CRITICAL',
    clusterDisposition: 'merge_redirect',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c41',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-examples-in-healthcare',
    canonicalSlug: 'ai-agents-examples-in-healthcare',
    canonicalUrl: '/ai-agents-examples-in-healthcare',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['industry:healthcare'],
    relatedEntityIds: ['concept:medical-ai', 'concept:healthcare-technology'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'retarget',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c42',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-examples-in-real-estate',
    canonicalSlug: 'ai-agents-examples-in-real-estate',
    canonicalUrl: '/ai-agents-examples-in-real-estate',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['industry:real-estate'],
    relatedEntityIds: ['concept:property-tech', 'concept:proptech'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'retarget',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c43',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-examples-in-banking',
    canonicalSlug: 'ai-agents-examples-in-banking',
    canonicalUrl: '/ai-agents-examples-in-banking',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['industry:banking'],
    relatedEntityIds: ['concept:fintech', 'concept:banking-technology'],
    requiredEvidenceClass: 'CRITICAL',
    clusterDisposition: 'retarget',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c44',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-examples-in-education',
    canonicalSlug: 'ai-agents-examples-in-education',
    canonicalUrl: '/ai-agents-examples-in-education',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['industry:education'],
    relatedEntityIds: ['concept:edtech', 'concept:learning-technology'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'retarget',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c45',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-examples-in-retail',
    canonicalSlug: 'ai-agents-examples-in-retail',
    canonicalUrl: '/ai-agents-examples-in-retail',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['industry:retail'],
    relatedEntityIds: ['concept:ecommerce', 'concept:retail-technology'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'retarget',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c46',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-examples-in-insurance',
    canonicalSlug: 'ai-agents-examples-in-insurance',
    canonicalUrl: '/ai-agents-examples-in-insurance',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['industry:insurance'],
    relatedEntityIds: ['concept:insurtech', 'concept:insurance-technology'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'retarget',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c47',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-examples-in-manufacturing',
    canonicalSlug: 'ai-agents-examples-in-manufacturing',
    canonicalUrl: '/ai-agents-examples-in-manufacturing',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['industry:manufacturing'],
    relatedEntityIds: ['concept:industrial-ai', 'concept:smart-manufacturing'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'retarget',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c48',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-examples-in-travel',
    canonicalSlug: 'ai-agents-examples-in-travel',
    canonicalUrl: '/ai-agents-examples-in-travel',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['industry:travel'],
    relatedEntityIds: ['concept:travel-tech', 'concept:tourism-technology'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'retarget',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c49',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-examples-in-legal',
    canonicalSlug: 'ai-agents-examples-in-legal',
    canonicalUrl: '/ai-agents-examples-in-legal',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['industry:legal'],
    relatedEntityIds: ['concept:legal-tech', 'concept:law-firm-technology'],
    requiredEvidenceClass: 'CRITICAL',
    clusterDisposition: 'retarget',
    lastReviewed: '2026-08-22',
  },
  {
    inventoryId: 'p01-c50',
    group: 'core',
    pillarId: 'p01',
    pageClass: 'cluster',
    searchIntent: 'informational',
    originalSlug: 'ai-agents-examples-in-logistics',
    canonicalSlug: 'ai-agents-examples-in-logistics',
    canonicalUrl: '/ai-agents-examples-in-logistics',
    parentPillarSlug: 'ai-agents',
    lifecycleStatus: 'evidence_ready',
    publicationEligible: false,
    redirectFrom: [],
    primaryEntityIds: ['industry:logistics'],
    relatedEntityIds: ['concept:supply-chain', 'concept:transportation-technology'],
    requiredEvidenceClass: 'STANDARD',
    clusterDisposition: 'retarget',
    lastReviewed: '2026-08-22',
  }
];

/**
 * Get registry summary for the authoritative CONTENT_REGISTRY only.
 * This is what the gate verification script expects.
 */
export function registrySummary() {
  const byGroup = new Map<ContentGroup, number>();
  const byStatus = new Map<LifecycleStatus, number>();
  const byEvidence = new Map<EvidenceClass, number>();
  for (const r of CONTENT_REGISTRY) {
    byGroup.set(r.group, (byGroup.get(r.group) ?? 0) + 1);
    byStatus.set(r.lifecycleStatus, (byStatus.get(r.lifecycleStatus) ?? 0) + 1);
    byEvidence.set(r.requiredEvidenceClass, (byEvidence.get(r.requiredEvidenceClass) ?? 0) + 1);
  }
  return {
    total: CONTENT_REGISTRY.length,
    byGroup: Object.fromEntries(byGroup),
    byStatus: Object.fromEntries(byStatus),
    byEvidence: Object.fromEntries(byEvidence),
    indexable: CONTENT_REGISTRY.filter((r) => r.publicationEligible).length,
    quarantined: CONTENT_REGISTRY.filter((r) => r.lifecycleStatus === 'quarantined_template').length,
  };
}

/**
 * Get the combined registry for reporting purposes.
 * This merges the authoritative CSV-derived registry with the drafted overlay.
 * 
 * NOTE: For publication eligibility and canonical decisions, only the
 * authoritative registry (P01_CLASSIFICATIONS -> CONTENT_REGISTRY) should be used.
 * The drafted overlay is for tracking editorial work-in-progress only.
 */
export function getCombinedRegistry(): ContentRecord[] {
  return [...CONTENT_REGISTRY, ...DRAFTED_CLUSTER_OVERLAY];
}

/**
 * Get registry summary for the combined set.
 */
export function combinedRegistrySummary() {
  const combined = getCombinedRegistry();
  const byGroup = new Map<ContentGroup, number>();
  const byStatus = new Map<LifecycleStatus, number>();
  const byEvidence = new Map<EvidenceClass, number>();
  for (const r of combined) {
    byGroup.set(r.group, (byGroup.get(r.group) ?? 0) + 1);
    byStatus.set(r.lifecycleStatus, (byStatus.get(r.lifecycleStatus) ?? 0) + 1);
    byEvidence.set(r.requiredEvidenceClass, (byEvidence.get(r.requiredEvidenceClass) ?? 0) + 1);
  }
  return {
    total: combined.length,
    byGroup: Object.fromEntries(byGroup),
    byStatus: Object.fromEntries(byStatus),
    byEvidence: Object.fromEntries(byEvidence),
    indexable: combined.filter((r) => r.publicationEligible).length,
    quarantined: combined.filter((r) => r.lifecycleStatus === 'quarantined_template').length,
  };
}