/**
 * ATLAS W1 — Pillar 01 cluster classification (CSV-derived).
 * 
 * Source of truth: reports/p01-authoritative-inventory.csv
 * Generated by: scripts/generate-p01-classification.ts
 * 
 * This file contains classifications for all 50 authoritative P01 clusters
 * (topic_index 1-50 from the CSV). Editorial expansion pages are maintained
 * separately in the overlay registry and do not replace these inventory rows.
 */

export type ClusterDisposition =
  | 'build_now'
  | 'needs_more_research'
  | 'merge_redirect'
  | 'retarget'
  | 'reject';

export interface P01ClusterClassification {
  topicIndex: number;
  slug: string;
  title: string;
  disposition: ClusterDisposition;
  reason: string;
  intentGroup: 'persona' | 'workflow' | 'generated-question' | 'industry';
  mergeTarget?: string;
  retargetPillar?: string;
  retargetSlug?: string;
}

/**
 * Authoritative 50-cluster classification.
 * Derived from reports/p01-authoritative-inventory.csv (topic_index 1..50).
 */
export const P01_CLASSIFICATIONS: P01ClusterClassification[] = [
  // topic_index 1
  {
    topicIndex: 1,
    slug: "ai-agents-for-startups",
    title: "AI Agents For Startups",
    disposition: "build_now",
    reason: "Distinct persona with evidence-backed vendor pricing already in ledger.",
    intentGroup: "persona",
  },

  // topic_index 2
  {
    topicIndex: 2,
    slug: "ai-agents-for-small-business",
    title: "AI Agents For Small Business",
    disposition: "needs_more_research",
    reason: "Persona-specific evidence required; deferred to persona wave.",
    intentGroup: "persona",
  },

  // topic_index 3
  {
    topicIndex: 3,
    slug: "ai-agents-for-enterprises",
    title: "AI Agents For Enterprises",
    disposition: "needs_more_research",
    reason: "Persona-specific evidence required; deferred to persona wave.",
    intentGroup: "persona",
  },

  // topic_index 4
  {
    topicIndex: 4,
    slug: "ai-agents-for-solopreneurs",
    title: "AI Agents For Solopreneurs",
    disposition: "needs_more_research",
    reason: "Persona-specific evidence required; deferred to persona wave.",
    intentGroup: "persona",
  },

  // topic_index 5
  {
    topicIndex: 5,
    slug: "ai-agents-for-freelancers",
    title: "AI Agents For Freelancers",
    disposition: "needs_more_research",
    reason: "Persona-specific evidence required; deferred to persona wave.",
    intentGroup: "persona",
  },

  // topic_index 6
  {
    topicIndex: 6,
    slug: "ai-agents-for-students",
    title: "AI Agents For Students",
    disposition: "needs_more_research",
    reason: "Persona-specific evidence required; deferred to persona wave.",
    intentGroup: "persona",
  },

  // topic_index 7
  {
    topicIndex: 7,
    slug: "ai-agents-for-developers",
    title: "AI Agents For Developers",
    disposition: "needs_more_research",
    reason: "Persona-specific evidence required; deferred to persona wave.",
    intentGroup: "persona",
  },

  // topic_index 8
  {
    topicIndex: 8,
    slug: "ai-agents-for-agencies",
    title: "AI Agents For Agencies",
    disposition: "needs_more_research",
    reason: "Persona-specific evidence required; deferred to persona wave.",
    intentGroup: "persona",
  },

  // topic_index 9
  {
    topicIndex: 9,
    slug: "ai-agents-for-consultants",
    title: "AI Agents For Consultants",
    disposition: "needs_more_research",
    reason: "Persona-specific evidence required; deferred to persona wave.",
    intentGroup: "persona",
  },

  // topic_index 10
  {
    topicIndex: 10,
    slug: "ai-agents-for-nonprofits",
    title: "AI Agents For Nonprofits",
    disposition: "needs_more_research",
    reason: "Persona-specific evidence required; deferred to persona wave.",
    intentGroup: "persona",
  },

  // topic_index 11
  {
    topicIndex: 11,
    slug: "ai-agents-for-ctos",
    title: "AI Agents For Ctos",
    disposition: "needs_more_research",
    reason: "Persona-specific evidence required; deferred to persona wave.",
    intentGroup: "persona",
  },

  // topic_index 12
  {
    topicIndex: 12,
    slug: "ai-agents-for-founders",
    title: "AI Agents For Founders",
    disposition: "merge_redirect",
    reason: "Intent overlaps with topic_index 1 (ai-agents-for-startups); merge.",
    intentGroup: "persona",
    mergeTarget: "ai-agents-for-startups",
  },

  // topic_index 13
  {
    topicIndex: 13,
    slug: "ai-agents-automation",
    title: "AI Agents Automation",
    disposition: "needs_more_research",
    reason: "Workflow-specific evidence required; deferred to workflow wave.",
    intentGroup: "workflow",
  },

  // topic_index 14
  {
    topicIndex: 14,
    slug: "ai-agents-workflow",
    title: "AI Agents Workflow",
    disposition: "merge_redirect",
    reason: "Duplicates /agentic-workflows; merge into the canonical sibling.",
    intentGroup: "workflow",
    mergeTarget: "agentic-workflows",
  },

  // topic_index 15
  {
    topicIndex: 15,
    slug: "ai-agents-lead-generation",
    title: "AI Agents Lead Generation",
    disposition: "needs_more_research",
    reason: "Workflow-specific evidence required; deferred to workflow wave.",
    intentGroup: "workflow",
  },

  // topic_index 16
  {
    topicIndex: 16,
    slug: "ai-agents-data-analysis",
    title: "AI Agents Data Analysis",
    disposition: "needs_more_research",
    reason: "Workflow-specific evidence required; deferred to workflow wave.",
    intentGroup: "workflow",
  },

  // topic_index 17
  {
    topicIndex: 17,
    slug: "ai-agents-reporting",
    title: "AI Agents Reporting",
    disposition: "needs_more_research",
    reason: "Workflow-specific evidence required; deferred to workflow wave.",
    intentGroup: "workflow",
  },

  // topic_index 18
  {
    topicIndex: 18,
    slug: "ai-agents-scheduling",
    title: "AI Agents Scheduling",
    disposition: "needs_more_research",
    reason: "Workflow-specific evidence required; deferred to workflow wave.",
    intentGroup: "workflow",
  },

  // topic_index 19
  {
    topicIndex: 19,
    slug: "ai-agents-onboarding",
    title: "AI Agents Onboarding",
    disposition: "needs_more_research",
    reason: "Workflow-specific evidence required; deferred to workflow wave.",
    intentGroup: "workflow",
  },

  // topic_index 20
  {
    topicIndex: 20,
    slug: "ai-agents-forecasting",
    title: "AI Agents Forecasting",
    disposition: "needs_more_research",
    reason: "Workflow-specific evidence required; deferred to workflow wave.",
    intentGroup: "workflow",
  },

  // topic_index 21
  {
    topicIndex: 21,
    slug: "ai-agents-compliance",
    title: "AI Agents Compliance",
    disposition: "needs_more_research",
    reason: "Workflow-specific evidence required; deferred to workflow wave.",
    intentGroup: "workflow",
  },

  // topic_index 22
  {
    topicIndex: 22,
    slug: "ai-agents-research",
    title: "AI Agents Research",
    disposition: "needs_more_research",
    reason: "Workflow-specific evidence required; deferred to workflow wave.",
    intentGroup: "workflow",
  },

  // topic_index 23
  {
    topicIndex: 23,
    slug: "ai-agents-content-creation",
    title: "AI Agents Content Creation",
    disposition: "needs_more_research",
    reason: "Workflow-specific evidence required; deferred to workflow wave.",
    intentGroup: "workflow",
  },

  // topic_index 24
  {
    topicIndex: 24,
    slug: "ai-agents-translation",
    title: "AI Agents Translation",
    disposition: "needs_more_research",
    reason: "Workflow-specific evidence required; deferred to workflow wave.",
    intentGroup: "workflow",
  },

  // topic_index 25
  {
    topicIndex: 25,
    slug: "ai-agents-fraud-detection",
    title: "AI Agents Fraud Detection",
    disposition: "needs_more_research",
    reason: "Workflow-specific evidence required; deferred to workflow wave.",
    intentGroup: "workflow",
  },

  // topic_index 26
  {
    topicIndex: 26,
    slug: "ai-agents-risk-management",
    title: "AI Agents Risk Management",
    disposition: "needs_more_research",
    reason: "Workflow-specific evidence required; deferred to workflow wave.",
    intentGroup: "workflow",
  },

  // topic_index 27
  {
    topicIndex: 27,
    slug: "ai-agents-personalization",
    title: "AI Agents Personalization",
    disposition: "needs_more_research",
    reason: "Workflow-specific evidence required; deferred to workflow wave.",
    intentGroup: "workflow",
  },

  // topic_index 28
  {
    topicIndex: 28,
    slug: "ai-agents-documentation",
    title: "AI Agents Documentation",
    disposition: "needs_more_research",
    reason: "Workflow-specific evidence required; deferred to workflow wave.",
    intentGroup: "workflow",
  },

  // topic_index 29
  {
    topicIndex: 29,
    slug: "ai-agents-invoicing",
    title: "AI Agents Invoicing",
    disposition: "needs_more_research",
    reason: "Workflow-specific evidence required; deferred to workflow wave.",
    intentGroup: "workflow",
  },

  // topic_index 30
  {
    topicIndex: 30,
    slug: "ai-agents-ticketing",
    title: "AI Agents Ticketing",
    disposition: "needs_more_research",
    reason: "Workflow-specific evidence required; deferred to workflow wave.",
    intentGroup: "workflow",
  },

  // topic_index 31
  {
    topicIndex: 31,
    slug: "ai-agents-auditing",
    title: "AI Agents Auditing",
    disposition: "needs_more_research",
    reason: "Workflow-specific evidence required; deferred to workflow wave.",
    intentGroup: "workflow",
  },

  // topic_index 32
  {
    topicIndex: 32,
    slug: "ai-agents-monitoring",
    title: "AI Agents Monitoring",
    disposition: "needs_more_research",
    reason: "Workflow-specific evidence required; deferred to workflow wave.",
    intentGroup: "workflow",
  },

  // topic_index 33
  {
    topicIndex: 33,
    slug: "what-is-an-ai-agent-ai-agents",
    title: "What Is An AI Agent AI Agents",
    disposition: "merge_redirect",
    reason: "Generated question slug; merge into /ai-agents or relevant section.",
    intentGroup: "generated-question",
    mergeTarget: "ai-agents",
  },

  // topic_index 34
  {
    topicIndex: 34,
    slug: "how-does-an-ai-agent-ai-agents",
    title: "How Does An AI Agent AI Agents",
    disposition: "merge_redirect",
    reason: "Generated question slug; merge into /ai-agents or relevant section.",
    intentGroup: "generated-question",
    mergeTarget: "ai-agents",
  },

  // topic_index 35
  {
    topicIndex: 35,
    slug: "why-use-an-ai-agent-ai-agents",
    title: "Why Use An AI Agent AI Agents",
    disposition: "merge_redirect",
    reason: "Generated question slug; merge into /ai-agents or relevant section.",
    intentGroup: "generated-question",
    mergeTarget: "ai-agents",
  },

  // topic_index 36
  {
    topicIndex: 36,
    slug: "is-an-ai-agent-ai-agents",
    title: "Is An AI Agent AI Agents",
    disposition: "merge_redirect",
    reason: "Generated question slug; merge into /ai-agents or relevant section.",
    intentGroup: "generated-question",
    mergeTarget: "ai-agents",
  },

  // topic_index 37
  {
    topicIndex: 37,
    slug: "can-an-ai-agent-ai-agents",
    title: "Can An AI Agent AI Agents",
    disposition: "merge_redirect",
    reason: "Generated question slug; merge into /ai-agents or relevant section.",
    intentGroup: "generated-question",
    mergeTarget: "ai-agents",
  },

  // topic_index 38
  {
    topicIndex: 38,
    slug: "should-you-use-an-ai-agent-ai-agents",
    title: "Should You Use An AI Agent AI Agents",
    disposition: "merge_redirect",
    reason: "Generated question slug; merge into /ai-agents or relevant section.",
    intentGroup: "generated-question",
    mergeTarget: "ai-agents-vs-chatbots",
  },

  // topic_index 39
  {
    topicIndex: 39,
    slug: "how-to-choose-an-ai-agent-ai-agents",
    title: "How To Choose An AI Agent AI Agents",
    disposition: "merge_redirect",
    reason: "Generated question slug; merge into /ai-agents or relevant section.",
    intentGroup: "generated-question",
    mergeTarget: "ai-agent-evaluation",
  },

  // topic_index 40
  {
    topicIndex: 40,
    slug: "how-secure-is-an-ai-agent-ai-agents",
    title: "How Secure Is An AI Agent AI Agents",
    disposition: "merge_redirect",
    reason: "Generated question slug; merge into /ai-agents or relevant section.",
    intentGroup: "generated-question",
    mergeTarget: "ai-agent-evaluation",
  },

  // topic_index 41
  {
    topicIndex: 41,
    slug: "ai-agents-examples-in-healthcare",
    title: "AI Agents Examples In Healthcare",
    disposition: "retarget",
    reason: "Industry intent; retarget to corresponding industry pillar when built.",
    intentGroup: "industry",
    retargetPillar: "tbd",
    retargetSlug: "tbd",
  },

  // topic_index 42
  {
    topicIndex: 42,
    slug: "ai-agents-examples-in-real-estate",
    title: "AI Agents Examples In Real Estate",
    disposition: "retarget",
    reason: "Industry intent; retarget to corresponding industry pillar when built.",
    intentGroup: "industry",
    retargetPillar: "tbd",
    retargetSlug: "tbd",
  },

  // topic_index 43
  {
    topicIndex: 43,
    slug: "ai-agents-examples-in-banking",
    title: "AI Agents Examples In Banking",
    disposition: "retarget",
    reason: "Industry intent; retarget to corresponding industry pillar when built.",
    intentGroup: "industry",
    retargetPillar: "tbd",
    retargetSlug: "tbd",
  },

  // topic_index 44
  {
    topicIndex: 44,
    slug: "ai-agents-examples-in-education",
    title: "AI Agents Examples In Education",
    disposition: "retarget",
    reason: "Industry intent; retarget to corresponding industry pillar when built.",
    intentGroup: "industry",
    retargetPillar: "tbd",
    retargetSlug: "tbd",
  },

  // topic_index 45
  {
    topicIndex: 45,
    slug: "ai-agents-examples-in-retail",
    title: "AI Agents Examples In Retail",
    disposition: "retarget",
    reason: "Industry intent; retarget to corresponding industry pillar when built.",
    intentGroup: "industry",
    retargetPillar: "tbd",
    retargetSlug: "tbd",
  },

  // topic_index 46
  {
    topicIndex: 46,
    slug: "ai-agents-examples-in-insurance",
    title: "AI Agents Examples In Insurance",
    disposition: "retarget",
    reason: "Industry intent; retarget to corresponding industry pillar when built.",
    intentGroup: "industry",
    retargetPillar: "tbd",
    retargetSlug: "tbd",
  },

  // topic_index 47
  {
    topicIndex: 47,
    slug: "ai-agents-examples-in-manufacturing",
    title: "AI Agents Examples In Manufacturing",
    disposition: "retarget",
    reason: "Industry intent; retarget to corresponding industry pillar when built.",
    intentGroup: "industry",
    retargetPillar: "tbd",
    retargetSlug: "tbd",
  },

  // topic_index 48
  {
    topicIndex: 48,
    slug: "ai-agents-examples-in-travel",
    title: "AI Agents Examples In Travel",
    disposition: "retarget",
    reason: "Industry intent; retarget to corresponding industry pillar when built.",
    intentGroup: "industry",
    retargetPillar: "tbd",
    retargetSlug: "tbd",
  },

  // topic_index 49
  {
    topicIndex: 49,
    slug: "ai-agents-examples-in-legal",
    title: "AI Agents Examples In Legal",
    disposition: "retarget",
    reason: "Industry intent; retarget to corresponding industry pillar when built.",
    intentGroup: "industry",
    retargetPillar: "tbd",
    retargetSlug: "tbd",
  },

  // topic_index 50
  {
    topicIndex: 50,
    slug: "ai-agents-examples-in-logistics",
    title: "AI Agents Examples In Logistics",
    disposition: "retarget",
    reason: "Industry intent; retarget to corresponding industry pillar when built.",
    intentGroup: "industry",
    retargetPillar: "tbd",
    retargetSlug: "tbd",
  }

];

// ---------------------------------------------------------------------------
// Audit invariants — enforced at module load.
//   - 50 entries, topic_index 1-50 continuous, no gaps
//   - All slugs unique (mutual exclusivity)
//   - All dispositions valid
//   - NO fabricated placeholders
//   - Intent groups correctly assigned by topic_index range
// ---------------------------------------------------------------------------
const _audit = (() => {
  const total = P01_CLASSIFICATIONS.length;
  if (total !== 50) {
    throw new Error(`P01_CLASSIFICATIONS must contain exactly 50 entries (one per authoritative cluster); got ${total}.`);
  }
  
  const unique = new Set(P01_CLASSIFICATIONS.map((c) => c.slug)).size;
  if (unique !== total) {
    throw new Error(`P01_CLASSIFICATIONS slugs must be unique; found ${unique} unique slugs among ${total} entries.`);
  }
  
  const indices = new Set<number>();
  for (const c of P01_CLASSIFICATIONS) {
    if (c.topicIndex < 1 || c.topicIndex > 50) {
      throw new Error(`P01_CLASSIFICATIONS entry "${c.slug}" has invalid topic_index ${c.topicIndex}; must be 1-50.`);
    }
    if (indices.has(c.topicIndex)) {
      throw new Error(`P01_CLASSIFICATIONS duplicate topic_index ${c.topicIndex}.`);
    }
    indices.add(c.topicIndex);
  }
  
  for (let i = 1; i <= 50; i++) {
    if (!indices.has(i)) {
      throw new Error(`P01_CLASSIFICATIONS missing topic_index ${i}; CSV-derived invariants require continuous 1..50 coverage.`);
    }
  }
  
  const valid: ClusterDisposition[] = ['build_now', 'needs_more_research', 'merge_redirect', 'retarget', 'reject'];
  for (const c of P01_CLASSIFICATIONS) {
    if (!valid.includes(c.disposition)) {
      throw new Error(`P01_CLASSIFICATIONS entry "${c.slug}" has invalid disposition "${c.disposition}".`);
    }
  }
  
  // Intent-group range enforcement.
  for (const c of P01_CLASSIFICATIONS) {
    const expected = (() => {
      if (c.topicIndex >= 1 && c.topicIndex <= 12) return 'persona';
      if (c.topicIndex >= 13 && c.topicIndex <= 32) return 'workflow';
      if (c.topicIndex >= 33 && c.topicIndex <= 40) return 'generated-question';
      if (c.topicIndex >= 41 && c.topicIndex <= 50) return 'industry';
      return null;
    })();
    if (expected !== c.intentGroup) {
      throw new Error(`P01_CLASSIFICATIONS "${c.slug}" topic_index=${c.topicIndex} expected intentGroup="${expected}" but got "${c.intentGroup}".`);
    }
  }
  
  return { total, unique, fabricatedSlots: 0 };
})();

/** Read-only audit result for callers (e.g. gate scripts). */
export const P01_AUDIT: { total: number; unique: number; reservedSlots: number } = {
  total: _audit.total,
  unique: _audit.unique,
  reservedSlots: _audit.fabricatedSlots,
};

/**
 * Tally of dispositions for reporting.
 */
export function classificationSummary() {
  const out = new Map<ClusterDisposition, number>();
  for (const c of P01_CLASSIFICATIONS) {
    out.set(c.disposition, (out.get(c.disposition) ?? 0) + 1);
  }
  return Object.fromEntries(out);
}

/**
 * Tally of intent groups for reporting.
 */
export function intentGroupSummary() {
  const out = new Map<P01ClusterClassification['intentGroup'], number>();
  for (const c of P01_CLASSIFICATIONS) {
    out.set(c.intentGroup, (out.get(c.intentGroup) ?? 0) + 1);
  }
  return Object.fromEntries(out);
}
