// ATLAS P01: types live in types.ts; re-exported here so all existing
// `import { RouteRecord } from './routeRegistry.js'` imports keep working.
export type {
  RouteType,
  PublicationStatus,
  SitemapGroup,
  RouteRecord,
} from './types.js';
import type { RouteRecord } from './types.js';

// 1. Central Canonical Route Registry
// ATLAS P01: This is the single source of truth. Dynamic routes in
// routeResolver.ts validate slugs against entityResolvers — arbitrary slugs
// are no longer synthesized as published.
export const canonicalRoutes: Record<string, RouteRecord> = {
  // ATLAS P02 complete — /a/ and /tools/ migrated, MCP redirects fixed.
  // --- Master Pillars & Hubs ---
  '/': {
    id: 'home',
    path: '/',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/',
    title: 'BestAIAgent.in - #1 AI Agent Directory, Rankings & India Pricing Index (2026)',
    description: 'India\'s premier independent AI agent evaluation registry. Benchmark latency, compare prices in INR (₹), and deploy top AI coding, voice, and workflow agents.',
    sitemapGroup: 'pages',
    view: 'home',
    updatedAt: '2026-07-23'
  },
  // ATLAS P01: directory hub pages (rendered client-side, must be canonical too)
  '/agents': {
    id: 'hub:agents',
    path: '/agents',
    type: 'directory',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents',
    title: 'AI Agents Directory & Index - BestAIAgent.in',
    description: 'Browse the complete directory of evaluated AI agents. Filter by category, compare benchmarks, and review India pricing.',
    sitemapGroup: 'pages',
    view: 'home', // Treat agents directory as home for now
    updatedAt: '2026-07-23'
  },
  '/categories': {
    id: 'hub:categories',
    path: '/categories',
    type: 'directory',
    status: 'published',
    indexable: true,
    canonicalPath: '/categories',
    title: 'AI Agent Categories Directory - BestAIAgent.in',
    description: 'Explore all AI agent categories: coding, voice, customer support, sales, automation, frameworks, and MCP servers.',
    sitemapGroup: 'pages',
    view: 'home', // Treat categories directory as home for now
    updatedAt: '2026-07-23'
  },
  '/best-ai-agent': {
    id: 'pillar:best-ai-agent',
    path: '/best-ai-agent',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/best-ai-agent',
    title: 'Best AI Agent 2026: Master Evaluation & Buying Guide - BestAIAgent.in',
    description: 'Definitive evaluation guide for top AI agents. Empirical latency benchmarks, tool use accuracy, security audits, and INR pricing models.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/best-ai-agent-for-business': {
    id: 'pillar:business',
    path: '/best-ai-agent-for-business',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/best-ai-agent-for-business',
    title: 'Best AI Agents for Business & SME Workflows (2026) - BestAIAgent.in',
    description: 'Top business AI agents for CRM, sales outreach, customer support, and administrative workflow automation in India.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/best-ai-agent-for-coding': {
    id: 'pillar:coding',
    path: '/best-ai-agent-for-coding',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/best-ai-agent-for-coding',
    title: 'Best AI Coding Agents (2026) - Cursor, Claude Code, Copilot & Windsurf',
    description: 'Comprehensive evaluation of top autonomous coding agents. Benchmark code quality, IDE context indexing, terminal execution, and pricing.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/best-ai-agent-alternatives': {
    id: 'pillar:alternatives',
    path: '/best-ai-agent-alternatives',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/best-ai-agent-alternatives',
    title: 'Best AI Agent Alternatives & Competitor Comparison Directory (2026)',
    description: 'Compare top alternatives to Cursor, ChatGPT, Claude, CrewAI, AutoGen, and LangGraph. Migration guides and pricing trade-offs.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/best-ai-agents-for-automation': {
    id: 'pillar:automation',
    path: '/best-ai-agents-for-automation',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/best-ai-agents-for-automation',
    title: 'Best AI Agents for Workflow Automation (2026) - BestAIAgent.in',
    description: 'Top workflow automation agents and visual orchestration builders including n8n, Flowise, Reclaim AI, and Dify.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/best-ai-agent-frameworks': {
    id: 'pillar:frameworks',
    path: '/best-ai-agent-frameworks',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/best-ai-agent-frameworks',
    title: 'Best AI Agent Frameworks (2026) - LangGraph, CrewAI, AutoGen & Pydantic AI',
    description: 'In-depth benchmark guide to multi-agent frameworks, open-source SDKs, state graph engines, and developer toolkits.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/mcp-directory': {
    id: 'pillar:mcp-directory',
    path: '/mcp-directory',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp-directory',
    title: 'Model Context Protocol (MCP) Server Directory & Hub - BestAIAgent.in',
    description: 'The definitive directory of Model Context Protocol (MCP) servers. Connect Claude, Cursor, and custom agents to GitHub, Postgres, Slack, and Drive.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },
  '/best-ai-agent-builder': {
    id: 'pillar:best-ai-agent-builder',
    path: '/best-ai-agent-builder',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/best-ai-agent-builder',
    title: 'Best AI Agent Builders (2026) - No-Code Platforms & Visual Design Tools - BestAIAgent.in',
    description: 'Top AI agent builders and no-code platforms for visual agent design, workflow automation, and custom agent creation without deep ML expertise.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/silos': {
    id: 'pillar:silos',
    path: '/silos',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/silos',
    title: 'AI Agent Silos - BestAIAgent.in',
    description: 'Explore categorized AI agent ecosystems including builders, frameworks, business agents, research tools, and MCP servers.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/silos/builders': {
    id: 'pillar:silos-builders',
    path: '/silos/builders',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/silos/builders',
    title: 'AI Agent Builders Silo - BestAIAgent.in',
    description: 'No-code and low-code AI agent builder platforms and visual design suites for creating custom agents without deep ML expertise.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/mcp-servers': {
    id: 'pillar:mcp-servers',
    path: '/mcp-servers',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp-servers',
    title: 'Verified MCP Servers Hub (2026) - BestAIAgent.in',
    description: 'Explore verified open-source and enterprise MCP servers for database indexing, API integration, and file system automation.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },
  '/frameworks': {
    id: 'pillar:frameworks-list',
    path: '/frameworks',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/frameworks',
    title: 'Open Source AI Agent Frameworks & SDKs Directory - BestAIAgent.in',
    description: 'Compare open source multi-agent frameworks: LangGraph, CrewAI, AutoGen, Flowise, Dify, and LlamaIndex.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/rankings': {
    id: 'pillar:rankings',
    path: '/rankings',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/rankings',
    title: 'Best AI Agent Leaderboards & Benchmark Rankings (2026) - BestAIAgent.in',
    description: 'Empirical rankings for AI coding agents, voice bots, and multi-agent frameworks based on latency, accuracy, and India fit.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/pricing': {
    id: 'hub:pricing',
    path: '/pricing',
    type: 'pricing',
    status: 'published',
    indexable: true,
    canonicalPath: '/pricing',
    title: 'India AI Agent Pricing Index in INR (₹) - BestAIAgent.in',
    description: 'Compare monthly subscription fees, token API costs, free tiers, and estimated monthly budgets in Indian Rupees (₹).',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/cursor-pricing': {
    id: 'pricing:cursor',
    path: '/cursor-pricing',
    type: 'pricing',
    status: 'published',
    indexable: true,
    canonicalPath: '/cursor-pricing',
    title: 'Cursor Pricing in India 2026: INR Plans & Cost Guide - BestAIAgent.in',
    description: 'Review Cursor pricing in India with INR estimates, plan comparisons, free-tier information, and cost context for Indian developers and teams.',
    sitemapGroup: 'pages',
    view: 'pricing',
    updatedAt: '2026-08-14'
  },
  '/github-copilot-pricing': {
    id: 'pricing:github-copilot',
    path: '/github-copilot-pricing',
    type: 'pricing',
    status: 'published',
    indexable: true,
    canonicalPath: '/github-copilot-pricing',
    title: 'GitHub Copilot Pricing in India 2026: INR Plans - BestAIAgent.in',
    description: 'Compare GitHub Copilot pricing in India with INR estimates, individual and business plan context, and India-focused purchasing guidance.',
    sitemapGroup: 'pages',
    view: 'pricing',
    updatedAt: '2026-08-14'
  },
  '/claude-code-pricing': {
    id: 'pricing:claude-code',
    path: '/claude-code-pricing',
    type: 'pricing',
    status: 'published',
    indexable: true,
    canonicalPath: '/claude-code-pricing',
    title: 'Claude Code Pricing in India 2026: INR Cost Guide - BestAIAgent.in',
    description: 'Understand Claude Code pricing for Indian developers with INR estimates, subscription and API cost context, and plan-selection guidance.',
    sitemapGroup: 'pages',
    view: 'pricing',
    updatedAt: '2026-08-14'
  },
  '/reviews': {
    id: 'pillar:reviews',
    path: '/reviews',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/reviews',
    title: 'AI Agent Reviews & Technical Audits Directory (2026) - BestAIAgent.in',
    description: 'Independent reviews and empirical test scores for evaluated AI agents, developer tools, and enterprise automation bots.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/compare': {
    id: 'hub:compare',
    path: '/compare',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/compare',
    title: 'AI Agent Head-to-Head Comparison Matrix (2026) - BestAIAgent.in',
    description: 'Compare top AI agents side-by-side. Benchmark reasoning speed, tool execution accuracy, security compliance, and pricing.',
    sitemapGroup: 'comparisons',
    updatedAt: '2026-07-23'
  },
  '/research': {
    id: 'hub:research',
    path: '/research',
    type: 'research',
    status: 'published',
    indexable: true,
    canonicalPath: '/research',
    title: 'AI Agent Market Intelligence & Benchmark Research Reports - BestAIAgent.in',
    description: 'In-depth empirical research, latency benchmarks, and enterprise AI adoption statistics across India and global markets.',
    sitemapGroup: 'research',
    updatedAt: '2026-07-23'
  },
  '/sitemap': {
    id: 'hub:sitemap',
    path: '/sitemap',
    type: 'governance',
    status: 'published',
    indexable: true,
    canonicalPath: '/sitemap',
    title: 'HTML Site Directory & Programmatic Knowledge Map - BestAIAgent.in',
    description: 'Complete HTML sitemap and knowledge index for BestAIAgent.in directory, category pillars, research reports, and comparison matrices.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },

  // --- Governance & Editorial Pages ---
  '/about': {
    id: 'gov:about',
    path: '/about',
    type: 'governance',
    status: 'published',
    indexable: true,
    canonicalPath: '/about',
    title: 'About BestAIAgent.in - Independent AI Agent Evaluation Registry',
    description: 'Learn about India\'s premier independent AI agent research authority, evaluation methodology, and editorial mission.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/authors': {
    id: 'hub:authors',
    path: '/authors',
    type: 'governance',
    status: 'published',
    indexable: true,
    canonicalPath: '/authors',
    title: 'Editorial Board & Technical Review Team - BestAIAgent.in',
    description: 'Meet our team of AI systems architects, software engineers, and security auditors who independently test and benchmark AI agents.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/methodology': {
    id: 'gov:methodology',
    path: '/methodology',
    type: 'governance',
    status: 'published',
    indexable: true,
    canonicalPath: '/methodology',
    title: 'Empirical Testing Methodology & Scoring Framework - BestAIAgent.in',
    description: 'Discover how we test AI agents: latency measuring protocols, tool execution accuracy benchmarks, security audits, and INR pricing calculation.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/editorial-policy': {
    id: 'gov:editorial-policy',
    path: '/editorial-policy',
    type: 'governance',
    status: 'published',
    indexable: true,
    canonicalPath: '/editorial-policy',
    title: 'Editorial Policy & Verification Standards - BestAIAgent.in',
    description: 'Our commitment to objective research, independence from vendor bias, AI-assisted content verification rules, and editorial integrity.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/review-process': {
    id: 'gov:review-process',
    path: '/review-process',
    type: 'governance',
    status: 'published',
    indexable: true,
    canonicalPath: '/review-process',
    title: 'AI Agent Review Process & Benchmark Guidelines - BestAIAgent.in',
    description: 'Step-by-step walkthrough of how our engineering team evaluates agent reasoning, workspace context memory, and production reliability.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/corrections': {
    id: 'gov:corrections',
    path: '/corrections',
    type: 'governance',
    status: 'published',
    indexable: true,
    canonicalPath: '/corrections',
    title: 'Corrections Policy & Fact-Checking Protocol - BestAIAgent.in',
    description: 'How we handle error reports, software update re-testing, price verification updates, and reader feedback.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/privacy-policy': {
    id: 'gov:privacy-policy',
    path: '/privacy-policy',
    type: 'governance',
    status: 'published',
    indexable: true,
    canonicalPath: '/privacy-policy',
    title: 'Privacy Policy & DPDP Act 2023 Compliance - BestAIAgent.in',
    description: 'Our privacy standards, cookie policies, and compliance with the Digital Personal Data Protection (DPDP) Act of India.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/terms': {
    id: 'gov:terms',
    path: '/terms',
    type: 'governance',
    status: 'published',
    indexable: true,
    canonicalPath: '/terms',
    title: 'Terms of Service - BestAIAgent.in',
    description: 'Terms and conditions for using BestAIAgent.in research directory, benchmarks, and interactive comparison engines.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/affiliate-disclosure': {
    id: 'gov:affiliate-disclosure',
    path: '/affiliate-disclosure',
    type: 'governance',
    status: 'published',
    indexable: true,
    canonicalPath: '/affiliate-disclosure',
    title: 'Affiliate & Financial Transparency Disclosure - BestAIAgent.in',
    description: 'Complete transparency regarding our business model, affiliate partnerships, and strict firewall between commercial relationships and benchmark ratings.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/contact': {
    id: 'gov:contact',
    path: '/contact',
    type: 'governance',
    status: 'published',
    indexable: true,
    canonicalPath: '/contact',
    title: 'Contact Editorial Office - BestAIAgent.in',
    description: 'Get in touch with our AI evaluation lab in Mumbai and Bangalore for tool submission, correction reports, or research inquiries.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/knowledge-graph': {
    id: 'gov:knowledge-graph',
    path: '/knowledge-graph',
    type: 'governance',
    status: 'published',
    indexable: true,
    canonicalPath: '/knowledge-graph',
    title: 'Semantic AI Knowledge Graph & Entity Index - BestAIAgent.in',
    description: 'Interactive semantic entity graph mapping relationships between AI agents, frameworks, models, vector stores, and MCP tools.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },

  // --- Category Hubs (/categories/[slug]) ---
  '/categories/coding-agents': {
    id: 'cat:coding-agents',
    path: '/categories/coding-agents',
    type: 'category',
    status: 'published',
    indexable: true,
    canonicalPath: '/categories/coding-agents',
    title: 'Best AI Coding Agents Directory & Benchmarks (2026) - BestAIAgent.in',
    description: 'Explore top autonomous coding agents for IDEs, terminal workflows, and full-stack software development.',
    sitemapGroup: 'categories',
    updatedAt: '2026-07-23'
  },
  '/categories/voice-bots': {
    id: 'cat:voice-bots',
    path: '/categories/voice-bots',
    type: 'category',
    status: 'published',
    indexable: true,
    canonicalPath: '/categories/voice-bots',
    title: 'Best Voice AI Agents & Telephony Bots (2026) - BestAIAgent.in',
    description: 'Sub-second latency voice bots supporting Hindi, Hinglish, Tamil, and English for customer support and inbound calls.',
    sitemapGroup: 'categories',
    updatedAt: '2026-07-23'
  },
  '/categories/orchestration': {
    id: 'cat:orchestration',
    path: '/categories/orchestration',
    type: 'category',
    status: 'published',
    indexable: true,
    canonicalPath: '/categories/orchestration',
    title: 'Best Multi-Agent Orchestration Frameworks (2026) - BestAIAgent.in',
    description: 'Frameworks and state machines for assembling collaborative multi-agent teams: LangGraph, CrewAI, AutoGen.',
    sitemapGroup: 'categories',
    updatedAt: '2026-07-23'
  },
  '/categories/business': {
    id: 'cat:business',
    path: '/categories/business',
    type: 'category',
    status: 'published',
    indexable: true,
    canonicalPath: '/categories/business',
    title: 'Business AI Agents Directory - BestAIAgent.in',
    description: 'AI agents for administrative tasks, sales pipelines, HR onboarding, and operational SME workflows.',
    sitemapGroup: 'categories',
    updatedAt: '2026-07-23'
  },
  '/categories/crm': {
    id: 'cat:crm',
    path: '/categories/crm',
    type: 'category',
    status: 'published',
    indexable: true,
    canonicalPath: '/categories/crm',
    title: 'Best CRM AI Agents (2026) - BestAIAgent.in',
    description: 'Automate lead qualification, sales activity logging, and client relationship pipelines in Salesforce, Zoho, and HubSpot.',
    sitemapGroup: 'categories',
    updatedAt: '2026-07-23'
  },
  '/categories/customer-support': {
    id: 'cat:customer-support',
    path: '/categories/customer-support',
    type: 'category',
    status: 'published',
    indexable: true,
    canonicalPath: '/categories/customer-support',
    title: 'Best Customer Support AI Agents (2026) - BestAIAgent.in',
    description: '24/7 customer support agents for WhatsApp, live chat, and voice helplines with DPDP compliance.',
    sitemapGroup: 'categories',
    updatedAt: '2026-07-23'
  },
  '/categories/sales': {
    id: 'cat:sales',
    path: '/categories/sales',
    type: 'category',
    status: 'published',
    indexable: true,
    canonicalPath: '/categories/sales',
    title: 'Best Sales & Outreach AI Agents (2026) - BestAIAgent.in',
    description: 'Automate prospect research, email sequencing, and meeting booking with autonomous sales agents.',
    sitemapGroup: 'categories',
    updatedAt: '2026-07-23'
  },
  '/categories/marketing': {
    id: 'cat:marketing',
    path: '/categories/marketing',
    type: 'category',
    status: 'published',
    indexable: true,
    canonicalPath: '/categories/marketing',
    title: 'Best Marketing AI Agents (2026) - BestAIAgent.in',
    description: 'Content generation, SEO research, social campaign automation, and ad creative optimization agents.',
    sitemapGroup: 'categories',
    updatedAt: '2026-07-23'
  },
  '/categories/research': {
    id: 'cat:research',
    path: '/categories/research',
    type: 'category',
    status: 'published',
    indexable: true,
    canonicalPath: '/categories/research',
    title: 'Best AI Agents for Deep Research & Analysis (2026) - BestAIAgent.in',
    description: 'Deep web research, document synthesis, competitive analysis, and academic literature review agents.',
    sitemapGroup: 'categories',
    updatedAt: '2026-07-23'
  },
  '/categories/automation': {
    id: 'cat:automation',
    path: '/categories/automation',
    type: 'category',
    status: 'published',
    indexable: true,
    canonicalPath: '/categories/automation',
    title: 'Workflow Automation & No-Code AI Builders - BestAIAgent.in',
    description: 'Visual flow engines, API trigger tools, and RPA bots for enterprise process automation.',
    sitemapGroup: 'categories',
    updatedAt: '2026-07-23'
  },

  // --- Agent Entity Pages (/agents/[slug]) ---
  '/agents/cursor': {
    id: 'agent:cursor',
    path: '/agents/cursor',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/cursor',
    title: 'Cursor AI Review, Benchmarks & India Pricing (2026) - BestAIAgent.in',
    description: 'Technical audit of Cursor AI. Workspace context indexing, Composer multi-file editing, latency, and INR pricing (₹1,680/mo).',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },
  '/agents/claude-code': {
    id: 'agent:claude-code',
    path: '/agents/claude-code',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/claude-code',
    title: 'Claude Code Agent Review, Terminal Execution & Benchmarks - BestAIAgent.in',
    description: 'In-depth review of Anthropic\'s Claude Code CLI agent. Multi-file refactoring, subshell execution, and cost analysis.',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },
  '/agents/chatgpt': {
    id: 'agent:chatgpt',
    path: '/agents/chatgpt',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/chatgpt',
    title: 'ChatGPT Agent Mode Review & India Pricing (2026) - BestAIAgent.in',
    description: 'Evaluation of OpenAI\'s agentic capabilities, web canvas, memory, custom GPT workflows, and INR pricing.',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },
  '/agents/claude': {
    id: 'agent:claude',
    path: '/agents/claude',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/claude',
    title: 'Claude 3.7 Sonnet & Artifacts Review - BestAIAgent.in',
    description: 'Full audit of Anthropic Claude. Hybrid reasoning, Computer Use API, system prompts, and benchmark scores.',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },
  '/agents/vapi': {
    id: 'agent:vapi',
    path: '/agents/vapi',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/vapi',
    title: 'Vapi AI Review: Voice Bot Latency & Hinglish Test (2026) - BestAIAgent.in',
    description: 'Technical review of Vapi.ai voice infrastructure. Sub-second audio latency, telephony integration, and INR costs.',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },
  '/agents/crewai': {
    id: 'agent:crewai',
    path: '/agents/crewai',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/crewai',
    title: 'CrewAI Framework Review & Multi-Agent Benchmarks - BestAIAgent.in',
    description: 'Audit of CrewAI open-source framework. Role-based orchestration, memory delegation, and production deployment.',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },
  '/agents/yellow-ai': {
    id: 'agent:yellow-ai',
    path: '/agents/yellow-ai',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/yellow-ai',
    title: 'Yellow.ai Enterprise WhatsApp Bot Review & Pricing - BestAIAgent.in',
    description: 'Review of Yellow.ai conversational bot platform. Indian enterprise WhatsApp API support, UPI payments, and DPDP compliance.',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },
  '/agents/flowise-ai': {
    id: 'agent:flowise-ai',
    path: '/agents/flowise-ai',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/flowise-ai',
    title: 'Flowise AI Review: No-Code Visual RAG & Flow Engine - BestAIAgent.in',
    description: 'Technical evaluation of Flowise. Open-source drag-and-drop orchestration, vector store connectors, and self-hosting.',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },
  '/agents/reclaim-ai': {
    id: 'agent:reclaim-ai',
    path: '/agents/reclaim-ai',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/reclaim-ai',
    title: 'Reclaim AI Review: Autonomous Calendar & Time Protection - BestAIAgent.in',
    description: 'Audit of Reclaim AI scheduling agent. Habit protection, meeting buffer management, and Google Calendar sync.',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },
  '/agents/n8n': {
    id: 'agent:n8n',
    path: '/agents/n8n',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/n8n',
    title: 'n8n AI Workflows Review: Open Source Automation Hub - BestAIAgent.in',
    description: 'Review of n8n AI agent nodes, self-hosted automation workflows, webhook triggers, and enterprise integration.',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },
  '/agents/relevance-ai': {
    id: 'agent:relevance-ai',
    path: '/agents/relevance-ai',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/relevance-ai',
    title: 'Relevance AI Review: No-Code B2B Agent Workforce - BestAIAgent.in',
    description: 'Evaluation of Relevance AI platform for building B2B research, sales, and content workforce pipelines.',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },
  '/agents/langgraph': {
    id: 'agent:langgraph',
    path: '/agents/langgraph',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/langgraph',
    title: 'LangGraph Review: Statechart Multi-Agent Engine - BestAIAgent.in',
    description: 'Technical deep dive into LangGraph state machines, cyclical agent workflows, human-in-the-loop controls, and LangSmith.',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },
  '/agents/autogen': {
    id: 'agent:autogen',
    path: '/agents/autogen',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/autogen',
    title: 'Microsoft AutoGen Review & Multi-Agent Benchmarks - BestAIAgent.in',
    description: 'Audit of Microsoft AutoGen. Conversational multi-agent framework, code execution sandboxes, and enterprise fit.',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },
  '/agents/windsurf': {
    id: 'agent:windsurf',
    path: '/agents/windsurf',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/windsurf',
    title: 'Windsurf IDE (Codeium) Review & Benchmarks - BestAIAgent.in',
    description: 'Review of Windsurf IDE agent cascade system, real-time code context indexing, and developer productivity scores.',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },
  '/agents/retell-ai': {
    id: 'agent:retell-ai',
    path: '/agents/retell-ai',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/retell-ai',
    title: 'Retell AI Voice Bot Review & Telephony Infrastructure - BestAIAgent.in',
    description: 'Audit of Retell AI voice engine. Conversation latency benchmarks, websockets API, and regional accent performance.',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },

  // --- Comparison Pages (/compare/[slug]) ---
  '/compare/cursor-vs-copilot': {
    id: 'cmp:cursor-vs-copilot',
    path: '/compare/cursor-vs-copilot',
    type: 'comparison',
    status: 'published',
    indexable: true,
    canonicalPath: '/compare/cursor-vs-copilot',
    title: 'Cursor AI vs GitHub Copilot: Head-to-Head Benchmark (2026) - BestAIAgent.in',
    description: 'Empirical comparison between Cursor AI and GitHub Copilot. Multi-file edits, indexing speed, IDE integration, and pricing.',
    sitemapGroup: 'comparisons',
    updatedAt: '2026-07-23'
  },
  '/compare/chatgpt-vs-claude': {
    id: 'cmp:chatgpt-vs-claude',
    path: '/compare/chatgpt-vs-claude',
    type: 'comparison',
    status: 'published',
    indexable: true,
    canonicalPath: '/compare/chatgpt-vs-claude',
    title: 'ChatGPT vs Claude 3.7 Sonnet: Agent Benchmark Test (2026) - BestAIAgent.in',
    description: 'Compare OpenAI ChatGPT (GPT-4o) vs Anthropic Claude 3.7 Sonnet. Reasoning tests, code generation, pricing, and API speeds.',
    sitemapGroup: 'comparisons',
    updatedAt: '2026-07-23'
  },
  '/compare/crewai-vs-autogen': {
    id: 'cmp:crewai-vs-autogen',
    path: '/compare/crewai-vs-autogen',
    type: 'comparison',
    status: 'published',
    indexable: true,
    canonicalPath: '/compare/crewai-vs-autogen',
    title: 'CrewAI vs AutoGen: Multi-Agent Framework Battle - BestAIAgent.in',
    description: 'Compare CrewAI vs Microsoft AutoGen. Developer experience, Python architecture, memory delegation, and production readiness.',
    sitemapGroup: 'comparisons',
    updatedAt: '2026-07-23'
  },
  '/compare/langgraph-vs-crewai': {
    id: 'cmp:langgraph-vs-crewai',
    path: '/compare/langgraph-vs-crewai',
    type: 'comparison',
    status: 'published',
    indexable: true,
    canonicalPath: '/compare/langgraph-vs-crewai',
    title: 'LangGraph vs CrewAI: Which Framework Should You Choose? - BestAIAgent.in',
    description: 'State graph control vs role-based agent crews. Benchmarks, memory persistence, and enterprise scalability analysis.',
    sitemapGroup: 'comparisons',
    updatedAt: '2026-07-23'
  },
  '/compare/vapi-vs-retell': {
    id: 'cmp:vapi-vs-retell',
    path: '/compare/vapi-vs-retell',
    type: 'comparison',
    status: 'published',
    indexable: true,
    canonicalPath: '/compare/vapi-vs-retell',
    title: 'Vapi AI vs Retell AI: Voice Bot Sub-Second Latency Test - BestAIAgent.in',
    description: 'Head-to-head voice AI test. Audio response latency, Hinglish dialect accuracy, phone trunking, and per-minute costs.',
    sitemapGroup: 'comparisons',
    updatedAt: '2026-07-23'
  },
  '/compare/flowise-vs-dify': {
    id: 'cmp:flowise-vs-dify',
    path: '/compare/flowise-vs-dify',
    type: 'comparison',
    status: 'published',
    indexable: true,
    canonicalPath: '/compare/flowise-vs-dify',
    title: 'Flowise AI vs Dify: Open Source Visual Agent Builders - BestAIAgent.in',
    description: 'Compare drag-and-drop orchestration tools Flowise AI and Dify. RAG pipelines, model support, and self-hosting options.',
    sitemapGroup: 'comparisons',
    updatedAt: '2026-07-23'
  },

  // --- MCP Servers (/mcp/servers/[slug]) ---
  '/mcp/servers/github': {
    id: 'mcp:github',
    path: '/mcp/servers/github',
    type: 'mcp-server',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp/servers/github',
    title: 'GitHub MCP Server: Configuration & Setup Guide - BestAIAgent.in',
    description: 'Connect Claude and Cursor to GitHub using official MCP server. Manage pull requests, issues, and repo search.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },
  '/mcp/servers/postgres': {
    id: 'mcp:postgres',
    path: '/mcp/servers/postgres',
    type: 'mcp-server',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp/servers/postgres',
    title: 'PostgreSQL MCP Server: Read/Write Database Integration - BestAIAgent.in',
    description: 'Query Postgres databases safely via MCP protocol. Schema inspection, read-only guards, and sample configurations.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },
  '/mcp/servers/slack': {
    id: 'mcp:slack',
    path: '/mcp/servers/slack',
    type: 'mcp-server',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp/servers/slack',
    title: 'Slack MCP Server: Workspace Integration & Channel Reader - BestAIAgent.in',
    description: 'Integrate Claude and local agents into Slack channels via MCP protocol. Post updates, read threads, and search messages.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },
  '/mcp/servers/filesystem': {
    id: 'mcp:filesystem',
    path: '/mcp/servers/filesystem',
    type: 'mcp-server',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp/servers/filesystem',
    title: 'Local Filesystem MCP Server Setup & Security Controls - BestAIAgent.in',
    description: 'Secure local filesystem access for AI desktop assistants. Allowed directory boundaries and file permission guards.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },
  '/mcp/servers/notion': {
    id: 'mcp:notion',
    path: '/mcp/servers/notion',
    type: 'mcp-server',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp/servers/notion',
    title: 'Notion MCP Server Setup & Integration Guide - BestAIAgent.in',
    description: 'Connect Claude and AI agents to Notion workspaces via MCP protocol. Read/write pages, databases, and search workspace content.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },
  '/mcp/servers/excel': {
    id: 'mcp:excel',
    path: '/mcp/servers/excel',
    type: 'mcp-server',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp/servers/excel',
    title: 'Excel MCP Server Setup & Spreadsheet Automation - BestAIAgent.in',
    description: 'Programmatic Excel and spreadsheet operations via MCP server. Read, write, and analyze spreadsheet data with AI agents.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },
  '/mcp/servers/shopify': {
    id: 'mcp:shopify',
    path: '/mcp/servers/shopify',
    type: 'mcp-server',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp/servers/shopify',
    title: 'Shopify MCP Server Setup & E-Commerce Integration - BestAIAgent.in',
    description: 'Connect AI agents to Shopify stores via MCP protocol. Manage products, orders, customers, and inventory programmatically.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },

  // --- Research Reports (/research/[slug]) ---
  '/research/state-of-ai-agents-india-2026': {
    id: 'research:india-2026',
    path: '/research/state-of-ai-agents-india-2026',
    type: 'research',
    status: 'published',
    indexable: true,
    canonicalPath: '/research/state-of-ai-agents-india-2026',
    title: 'State of AI Agents in India (2026) Market Research Report - BestAIAgent.in',
    description: 'Empirical industry report analyzing enterprise AI agent adoption, DPDP Act compliance, local cloud nodes, and ROI across Indian tech centers.',
    sitemapGroup: 'research',
    updatedAt: '2026-07-23'
  },
  '/research/voice-latency-report': {
    id: 'research:voice-latency',
    path: '/research/voice-latency-report',
    type: 'research',
    status: 'published',
    indexable: true,
    canonicalPath: '/research/voice-latency-report',
    title: 'Sub-Second Voice Bot Latency Benchmark Report - BestAIAgent.in',
    description: 'Benchmark measuring real audio response delay across Vapi, Retell, Bland AI, and regional voice engines under various network conditions.',
    sitemapGroup: 'research',
    updatedAt: '2026-07-23'
  },

  // --- ATLAS P02: Additional agent entity routes (preserve Search Console equity) ---
  '/agents/github-copilot': {
    id: 'agent:github-copilot',
    path: '/agents/github-copilot',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/github-copilot',
    title: 'GitHub Copilot Review, Agent Mode & India Pricing (2026) - BestAIAgent.in',
    description: 'Audit of GitHub Copilot AI pair programmer. Inline code completion, Chat workspace agent, multi-file edits, and INR pricing.',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },
  '/agents/intercom-ai': {
    id: 'agent:intercom-ai',
    path: '/agents/intercom-ai',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/intercom-ai',
    title: 'Intercom Fin AI Agent Review & Pricing - BestAIAgent.in',
    description: 'Review of Intercom Fin AI customer support agent. Resolution automation, conversational coverage, and INR pricing.',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },
  '/agents/codex': {
    id: 'agent:codex',
    path: '/agents/codex',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/codex',
    title: 'OpenAI Codex CLI Agent Review & Benchmarks - BestAIAgent.in',
    description: 'Audit of OpenAI Codex CLI coding agent. Containerized code execution, multi-repo PR workflow, and per-task pricing.',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },
  '/agents/replit': {
    id: 'agent:replit',
    path: '/agents/replit',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/replit',
    title: 'Replit AI Agent Review: Autonomous App Builder (2026) - BestAIAgent.in',
    description: 'Evaluation of Replit Agent autonomous coding capability. End-to-end app generation, deployment, and cloud workspace integration.',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },
  '/agents/agentops': {
    id: 'agent:agentops',
    path: '/agents/agentops',
    type: 'agent',
    status: 'published',
    indexable: true,
    canonicalPath: '/agents/agentops',
    title: 'AgentOps Review: AI Agent Observability & Eval Platform - BestAIAgent.in',
    description: 'Audit of AgentOps agent monitoring platform. Session replay, token cost tracking, LLM call tracing, and regression evaluation.',
    sitemapGroup: 'agents',
    updatedAt: '2026-07-23'
  },

  // --- ATLAS P02: Additional MCP server canonical routes ---
  '/mcp/servers/tally-prime-desktop-local-stdio': {
    id: 'mcp:tally-prime-desktop-local-stdio',
    path: '/mcp/servers/tally-prime-desktop-local-stdio',
    type: 'mcp-server',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp/servers/tally-prime-desktop-local-stdio',
    title: 'Tally Prime MCP Server (Desktop Local stdio) - BestAIAgent.in',
    description: 'Connect AI agents to Tally Prime desktop accounting via local stdio MCP server. Ledger read/write, GST return queries, and India SME integration.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },
  '/mcp/servers/xero-accounting-ledger-integrator': {
    id: 'mcp:xero-accounting-ledger-integrator',
    path: '/mcp/servers/xero-accounting-ledger-integrator',
    type: 'mcp-server',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp/servers/xero-accounting-ledger-integrator',
    title: 'Xero Accounting Ledger Integrator MCP Server - BestAIAgent.in',
    description: 'Programmatic ledger access to Xero accounting via MCP protocol. Invoice, contact, and bank transaction endpoints for AI agents.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },
  '/mcp/servers/databricks-delta-lake-pipeline': {
    id: 'mcp:databricks-delta-lake-pipeline',
    path: '/mcp/servers/databricks-delta-lake-pipeline',
    type: 'mcp-server',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp/servers/databricks-delta-lake-pipeline',
    title: 'Databricks Delta Lake Pipeline MCP Server - BestAIAgent.in',
    description: 'Orchestrate Databricks Delta Lake pipelines from AI agents via MCP. ETL job triggering, table reads, and schema introspection.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },
  '/mcp/servers/snyk-open-source-dependency-shield': {
    id: 'mcp:snyk-open-source-dependency-shield',
    path: '/mcp/servers/snyk-open-source-dependency-shield',
    type: 'mcp-server',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp/servers/snyk-open-source-dependency-shield',
    title: 'Snyk Open Source Dependency Shield MCP Server - BestAIAgent.in',
    description: 'AI-driven vulnerability scanning of open source dependencies via Snyk MCP. CVE lookup, license policy checks, and remediation suggestions.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },
  '/mcp/servers/aadhaar-ekyc-regulatory-sandbox': {
    id: 'mcp:aadhaar-ekyc-regulatory-sandbox',
    path: '/mcp/servers/aadhaar-ekyc-regulatory-sandbox',
    type: 'mcp-server',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp/servers/aadhaar-ekyc-regulatory-sandbox',
    title: 'Aadhaar eKYC Regulatory Sandbox MCP Server - BestAIAgent.in',
    description: 'UIDAI Aadhaar eKYC verification via MCP for AI agents in the regulatory sandbox. OTP/biometric flows, DPDP consent, and audit trails.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },
  '/mcp/servers/ecourts-india-njdg-document-scraper': {
    id: 'mcp:ecourts-india-njdg-document-scraper',
    path: '/mcp/servers/ecourts-india-njdg-document-scraper',
    type: 'mcp-server',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp/servers/ecourts-india-njdg-document-scraper',
    title: 'eCourts India NJDG Document Scraper MCP Server - BestAIAgent.in',
    description: 'Scrape eCourts India NJDG case status, orders, and judgments via MCP. Rate-limited access, case schema normalization, and agent integration.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },
  '/mcp/servers/fedex-ups-dhl-global-logistics': {
    id: 'mcp:fedex-ups-dhl-global-logistics',
    path: '/mcp/servers/fedex-ups-dhl-global-logistics',
    type: 'mcp-server',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp/servers/fedex-ups-dhl-global-logistics',
    title: 'FedEx UPS DHL Global Logistics MCP Server - BestAIAgent.in',
    description: 'Unified shipping API across FedEx, UPS, and DHL via MCP. Tracking, label generation, and rate shopping for AI agent workflows.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },
  '/mcp/servers/flexport-global-freight-forwarding': {
    id: 'mcp:flexport-global-freight-forwarding',
    path: '/mcp/servers/flexport-global-freight-forwarding',
    type: 'mcp-server',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp/servers/flexport-global-freight-forwarding',
    title: 'Flexport Global Freight Forwarding MCP Server - BestAIAgent.in',
    description: 'Flexport freight forwarding integration via MCP. Ocean/air shipment booking, customs documentation, and supply chain visibility.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },
  '/mcp/servers/supabase-firebase-schema-sync': {
    id: 'mcp:supabase-firebase-schema-sync',
    path: '/mcp/servers/supabase-firebase-schema-sync',
    type: 'mcp-server',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp/servers/supabase-firebase-schema-sync',
    title: 'Supabase Firebase Schema Sync MCP Server - BestAIAgent.in',
    description: 'Sync Supabase Postgres schemas with Firebase Firestore via MCP. Bidirectional schema diffing, migration tooling, and AI agent hooks.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },
  '/mcp/servers/corelogic-property-data-aggregator': {
    id: 'mcp:corelogic-property-data-aggregator',
    path: '/mcp/servers/corelogic-property-data-aggregator',
    type: 'mcp-server',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp/servers/corelogic-property-data-aggregator',
    title: 'CoreLogic Property Data Aggregator MCP Server - BestAIAgent.in',
    description: 'Aggregate CoreLogic property and mortgage data via MCP. AVM lookups, ownership records, and market analytics for real-estate AI agents.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },
  '/mcp/servers/pdf': {
    id: 'mcp:pdf',
    path: '/mcp/servers/pdf',
    type: 'mcp-server',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp/servers/pdf',
    title: 'PDF Processing MCP Server: Read, Extract & Generate - BestAIAgent.in',
    description: 'Programmatic PDF operations via MCP server. Page extraction, OCR, form filling, and document generation for AI agent workflows.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },
  '/mcp/servers/google-drive': {
    id: 'mcp:google-drive',
    path: '/mcp/servers/google-drive',
    type: 'mcp-server',
    status: 'published',
    indexable: true,
    canonicalPath: '/mcp/servers/google-drive',
    title: 'Google Drive AI Agent Workspace MCP Server - BestAIAgent.in',
    description: 'Connect AI agents to Google Drive via MCP. File search, document read/write, and workspace automation across Docs, Sheets, and Slides.',
    sitemapGroup: 'mcp',
    updatedAt: '2026-07-23'
  },

  // --- ATLAS P02: Additional comparison routes ---
  '/compare/cursor-vs-codex': {
    id: 'cmp:cursor-vs-codex',
    path: '/compare/cursor-vs-codex',
    type: 'comparison',
    status: 'published',
    indexable: true,
    canonicalPath: '/compare/cursor-vs-codex',
    title: 'Cursor AI vs OpenAI Codex CLI: Coding Agent Benchmark (2026) - BestAIAgent.in',
    description: 'Head-to-head coding agent benchmark. Cursor multi-file IDE context vs Codex containerized CLI execution, latency, and pricing.',
    sitemapGroup: 'comparisons',
    updatedAt: '2026-07-23'
  },
  '/compare/copilot-vs-codex': {
    id: 'cmp:copilot-vs-codex',
    path: '/compare/copilot-vs-codex',
    type: 'comparison',
    status: 'published',
    indexable: true,
    canonicalPath: '/compare/copilot-vs-codex',
    title: 'GitHub Copilot vs OpenAI Codex: AI Coding Agent Comparison - BestAIAgent.in',
    description: 'Compare GitHub Copilot inline IDE completion with OpenAI Codex CLI agent. Workflow fit, multi-repo support, and INR pricing.',
    sitemapGroup: 'comparisons',
    updatedAt: '2026-07-23'
  },
  '/compare/claude-code-vs-codex': {
    id: 'cmp:claude-code-vs-codex',
    path: '/compare/claude-code-vs-codex',
    type: 'comparison',
    status: 'published',
    indexable: true,
    canonicalPath: '/compare/claude-code-vs-codex',
    title: 'Claude Code vs OpenAI Codex CLI: Terminal Coding Agent Test - BestAIAgent.in',
    description: 'Terminal-native coding agent battle. Anthropic Claude Code vs OpenAI Codex CLI on refactor tasks, repo scale, and tokens-to-PR cost.',
    sitemapGroup: 'comparisons',
    updatedAt: '2026-07-23'
  },
  '/compare/chatgpt-vs-perplexity': {
    id: 'cmp:chatgpt-vs-perplexity',
    path: '/compare/chatgpt-vs-perplexity',
    type: 'comparison',
    status: 'published',
    indexable: true,
    canonicalPath: '/compare/chatgpt-vs-perplexity',
    title: 'ChatGPT vs Perplexity AI: Research Agent & Search Comparison - BestAIAgent.in',
    description: 'Compare OpenAI ChatGPT agent mode with Perplexity AI answer engine. Citation quality, web search depth, and India pricing.',
    sitemapGroup: 'comparisons',
    updatedAt: '2026-07-23'
  },
  '/compare/github-copilot-vs-tabnine': {
    id: 'cmp:github-copilot-vs-tabnine',
    path: '/compare/github-copilot-vs-tabnine',
    type: 'comparison',
    status: 'published',
    indexable: true,
    canonicalPath: '/compare/github-copilot-vs-tabnine',
    title: 'GitHub Copilot vs Tabnine: AI Code Completion Comparison - BestAIAgent.in',
    description: 'Compare GitHub Copilot vs Tabnine. On-prem deployment, privacy, language coverage, and per-seat INR pricing for Indian dev teams.',
    sitemapGroup: 'comparisons',
    updatedAt: '2026-07-23'
  },
  '/compare/github-copilot-vs-amazon-codewhisperer': {
    id: 'cmp:github-copilot-vs-amazon-codewhisperer',
    path: '/compare/github-copilot-vs-amazon-codewhisperer',
    type: 'comparison',
    status: 'published',
    indexable: true,
    canonicalPath: '/compare/github-copilot-vs-amazon-codewhisperer',
    title: 'GitHub Copilot vs Amazon CodeWhisperer: Cloud AI Coding Comparison - BestAIAgent.in',
    description: 'Compare GitHub Copilot with Amazon CodeWhisperer/Q Developer. AWS integration, security scans, multi-language support, and pricing.',
    sitemapGroup: 'comparisons',
    updatedAt: '2026-07-23'
  },
  '/compare/intercom-vs-freshdesk': {
    id: 'cmp:intercom-vs-freshdesk',
    path: '/compare/intercom-vs-freshdesk',
    type: 'comparison',
    status: 'published',
    indexable: true,
    canonicalPath: '/compare/intercom-vs-freshdesk',
    title: 'Intercom Fin AI vs Freshdesk Freddy AI: Support Agent Comparison - BestAIAgent.in',
    description: 'Compare Intercom Fin AI vs Freshdesk Freddy AI. Resolution rates, channeled automation, India support costs, and INR pricing.',
    sitemapGroup: 'comparisons',
    updatedAt: '2026-07-23'
  },
  '/compare/retell-ai-vs-elevenlabs': {
    id: 'cmp:retell-ai-vs-elevenlabs',
    path: '/compare/retell-ai-vs-elevenlabs',
    type: 'comparison',
    status: 'published',
    indexable: true,
    canonicalPath: '/compare/retell-ai-vs-elevenlabs',
    title: 'Retell AI vs ElevenLabs: Voice Bot & TTS Comparison - BestAIAgent.in',
    description: 'Compare Retell AI voice bot platform with ElevenLabs TTS. Conversation latency, voice cloning, multilingual Indic support, and costs.',
    sitemapGroup: 'comparisons',
    updatedAt: '2026-07-23'
  },
  '/compare/vapi-vs-synthflow': {
    id: 'cmp:vapi-vs-synthflow',
    path: '/compare/vapi-vs-synthflow',
    type: 'comparison',
    status: 'published',
    indexable: true,
    canonicalPath: '/compare/vapi-vs-synthflow',
    title: 'Vapi AI vs Synthflow: No-Code Voice Bot Comparison - BestAIAgent.in',
    description: 'Compare Vapi AI voice infrastructure with Synthflow no-code voice platform. Outbound calling, telephony, and INR per-minute pricing.',
    sitemapGroup: 'comparisons',
    updatedAt: '2026-07-23'
  },

  // --- ATLAS P02: Pillar/hub pages for India compliance & vertical use cases ---
  '/best-free-ai-agents': {
    id: 'pillar:best-free-ai-agents',
    path: '/best-free-ai-agents',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/best-free-ai-agents',
    title: 'Best Free AI Agents (2026): Open-Source & Free-Tier Directory - BestAIAgent.in',
    description: 'Curated list of free and open-source AI agents. Free-tier voice bots, coding agents, and automation frameworks with self-hostable options.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/best-ai-voice-agent': {
    id: 'pillar:best-ai-voice-agent',
    path: '/best-ai-voice-agent',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/best-ai-voice-agent',
    title: 'Best AI Voice Agent (2026): Sub-Second Latency & India Pricing - BestAIAgent.in',
    description: 'Independent ranking of AI voice agents. Vapi, Retell, Synthflow, and Indic voice engines benchmarked on latency and INR pricing.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/ai-agents-for-security': {
    id: 'pillar:ai-agents-for-security',
    path: '/ai-agents-for-security',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/ai-agents-for-security',
    title: 'AI Agents for Security: SOC Automation & Vulnerability Triage (2026) - BestAIAgent.in',
    description: 'AI agents for security operations. Vulnerability scanning, SOC alert triage, threat hunting, and DPDP-aligned data handling.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/india': {
    id: 'pillar:india',
    path: '/india',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/india',
    title: 'AI Agents in India: Market Directory, Pricing & DPDP Compliance (2026) - BestAIAgent.in',
    description: 'India-focused AI agent hub. INR pricing index, DPDP Act compliance notes, Tier-2 cloud nodes, and Indic language support across vendors.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/compliance/dpdp-act-ai-agents': {
    id: 'pillar:dpdp-act-ai-agents',
    path: '/compliance/dpdp-act-ai-agents',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/compliance/dpdp-act-ai-agents',
    title: 'DPDP Act Compliance for AI Agents (2026) - BestAIAgent.in',
    description: 'Compliance guide mapping India\'s DPDP Act to AI agent deployments. Consent flows, data residency, principal rights, and audit requirements.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/best-ai-agent-for-call-centers': {
    id: 'pillar:best-ai-agent-for-call-centers',
    path: '/best-ai-agent-for-call-centers',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/best-ai-agent-for-call-centers',
    title: 'Best AI Agent for Call Centers (2026): Voice Bots & Co-Pilot Comparison - BestAIAgent.in',
    description: 'AI agent selection for call centers. Inbound IVR handoff, agent-assist co-pilot, multilingual support, and INR per-minute economics.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/best-ai-agent-for-education': {
    id: 'pillar:best-ai-agent-for-education',
    path: '/best-ai-agent-for-education',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/best-ai-agent-for-education',
    title: 'Best AI Agent for Education (2026): Tutoring, Grading & Personalization - BestAIAgent.in',
    description: 'AI agents for education workflows. Adaptive tutoring, automated grading, multi-language Indic support, and student data privacy.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/best-ai-agent-for-real-estate-calls': {
    id: 'pillar:best-ai-agent-for-real-estate-calls',
    path: '/best-ai-agent-for-real-estate-calls',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/best-ai-agent-for-real-estate-calls',
    title: 'Best AI Agent for Real Estate Calls (2026): Lead Qualification & Follow-up - BestAIAgent.in',
    description: 'Voice AI for real estate outbound calling. Lead qualification scripts, Indian language coverage, DND compliance, and INR call cost.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  },
  '/best-ai-agent-course': {
    id: 'pillar:best-ai-agent-course',
    path: '/best-ai-agent-course',
    type: 'pillar',
    status: 'published',
    indexable: true,
    canonicalPath: '/best-ai-agent-course',
    title: 'Best AI Agent Course (2026): Build, Evaluate & Deploy Agents - BestAIAgent.in',
    description: 'Curated AI agent learning path. Frameworks, evaluation methodology, deployment patterns, and Indian instructor-led courses with INR pricing.',
    sitemapGroup: 'pages',
    updatedAt: '2026-07-23'
  }
};

// 2. Legacy Server-Side 301 Redirect Registry
// ATLAS P02 will migrate /a/ and /tools/ references and fix the wrong MCP
// redirects (notion→slack, excel→filesystem, shopify→github).
export const legacyRedirects: Record<string, string> = {
  // Legacy agent rankings
  '/ai-agent-rankings': '/rankings',
  '/ai-agent-rankings/': '/rankings',
  
  // Legacy /tools/ to /agents/ entity mapping
  '/tools/cursor': '/agents/cursor',
  '/tools/cursor-ai': '/agents/cursor',
  '/tools/claude-code': '/agents/claude-code',
  '/tools/chatgpt': '/agents/chatgpt',
  '/tools/claude': '/agents/claude',
  '/tools/vapi': '/agents/vapi',
  '/tools/vapi-ai': '/agents/vapi',
  '/tools/crewai': '/agents/crewai',
  '/tools/yellow-ai': '/agents/yellow-ai',
  '/tools/flowise': '/agents/flowise-ai',
  '/tools/flowise-ai': '/agents/flowise-ai',
  '/tools/reclaim-ai': '/agents/reclaim-ai',
  '/tools/n8n': '/agents/n8n',
  '/tools/relevance-ai': '/agents/relevance-ai',
  '/tools/langgraph': '/agents/langgraph',
  '/tools/autogen': '/agents/autogen',
  '/tools/windsurf': '/agents/windsurf',
  '/tools/retell-ai': '/agents/retell-ai',

  // Trailing slash legacy /tools/
  '/tools/cursor/': '/agents/cursor',
  '/tools/claude-code/': '/agents/claude-code',
  '/tools/chatgpt/': '/agents/chatgpt',
  '/tools/vapi/': '/agents/vapi',
  '/tools/crewai/': '/agents/crewai',
  '/tools/yellow-ai/': '/agents/yellow-ai',

  // Legacy /a/ routes
  '/a/best-ai-agent/reviews/chatgpt': '/agents/chatgpt',
  '/a/best-ai-agent/reviews/claude': '/agents/claude',
  '/a/best-ai-agent/reviews/cursor': '/agents/cursor',
  '/a/best-ai-agent/reviews/vapi': '/agents/vapi',
  '/a/best-ai-agent/reviews/crewai': '/agents/crewai',

  // Root MCP server legacy consolidation
  // ATLAS P02: fix these — redirects now point to semantically correct entities
  '/notion-server': '/mcp/servers/notion',
  '/excel-server': '/mcp/servers/excel',
  '/shopify-server': '/mcp/servers/shopify',

  // Keyword overlap consolidation
  '/best-ai-agent-for-crm': '/categories/crm',
  '/ai-agents-for-crm': '/categories/crm',
  '/best-ai-agent-for-sales': '/categories/sales',
  '/ai-agents-for-sales': '/categories/sales',
  '/best-ai-agent-for-marketing': '/categories/marketing',
  '/ai-agents-for-marketing': '/categories/marketing',
  '/glossary': '/sitemap',
  '/glossary-hub': '/sitemap',
  '/pricing-hub': '/pricing',
  '/pricing-intelligence': '/pricing',
  // Sitemap aliases
  '/sitemap.xml': '/sitemap-index.xml',
  '/sitemap-indexed.xml': '/sitemap-index.xml',

  // ATLAS P03: Search Console URL inventory preservation
  // These URLs have existing search impressions/clicks - redirect to preserve equity

  // Pricing pages → agent entity pages
  '/vapi-pricing': '/agents/vapi',
  '/n8n-pricing': '/agents/n8n',
  '/yellow-ai-pricing': '/agents/yellow-ai',
  '/intercom-pricing': '/agents/intercom-ai',
  '/retell-pricing': '/agents/retell-ai',
  '/flowise-pricing': '/agents/flowise-ai',
  '/langgraph-pricing': '/agents/langgraph',

  // Alternatives pages → agent entity pages
  '/cursor-alternatives': '/agents/cursor',
  '/claude-code-alternatives': '/agents/claude-code',
  '/codex-alternatives': '/agents/codex',
  '/flowise-alternatives': '/agents/flowise-ai',
  '/vapi-alternatives': '/agents/vapi',
  '/yellow-ai-alternatives': '/agents/yellow-ai',
  '/replit-alternatives': '/agents/replit',
  '/n8n-alternatives': '/agents/n8n',
  '/intercom-alternatives': '/agents/intercom-ai',
  '/github-copilot-alternatives': '/agents/github-copilot',

  // How-to pages → agent entity pages
  '/how-to-use-cursor-ai': '/agents/cursor',
  '/how-to-use-vapi': '/agents/vapi',
  '/how-to-use-github-copilot': '/agents/github-copilot',
  '/how-to-use-yellow-ai': '/agents/yellow-ai',
  '/how-to-build-ai-agent-with-flowise': '/agents/flowise-ai',
  '/how-to-create-mcp-server': '/mcp-directory',
  '/how-to-build-an-ai-agent': '/best-ai-agent-builder',

  // MCP pages → MCP server pages
  '/tally-prime-desktop-local-stdio-mcp': '/mcp/servers/tally-prime-desktop-local-stdio',
  '/xero-accounting-ledger-integrator-mcp': '/mcp/servers/xero-accounting-ledger-integrator',
  '/databricks-delta-lake-pipeline-mcp': '/mcp/servers/databricks-delta-lake-pipeline',
  '/snyk-open-source-dependency-shield-mcp': '/mcp/servers/snyk-open-source-dependency-shield',
  '/aadhaar-ekyc-regulatory-sandbox-mcp': '/mcp/servers/aadhaar-ekyc-regulatory-sandbox',
  '/ecourts-india-njdg-document-scraper-mcp': '/mcp/servers/ecourts-india-njdg-document-scraper',
  '/fedex-ups-dhl-global-logistics-mcp': '/mcp/servers/fedex-ups-dhl-global-logistics',
  '/flexport-global-freight-forwarding-mcp': '/mcp/servers/flexport-global-freight-forwarding',
  '/supabase-firebase-schema-sync-mcp': '/mcp/servers/supabase-firebase-schema-sync',
  '/corelogic-property-data-aggregator-mcp': '/mcp/servers/corelogic-property-data-aggregator',
  '/pdf-server': '/mcp/servers/pdf',
  '/google-drive-ai-agent-workspace': '/mcp/servers/google-drive',

  // Hub pages → relevant hub/category pages
  '/coding-agents-hub': '/categories/coding-agents',
  '/mcp-hub': '/mcp-directory',
  '/free-ai-agents-hub': '/best-free-ai-agents',
  '/business-ai-hub': '/categories/business',
  '/longtail-hub': '/sitemap',
  '/tutorials-hub': '/sitemap',
  '/reddit-hub': '/sitemap',
  '/industry-ai-agents-hub': '/categories',
  '/voice-ai-hub': '/best-ai-voice-agent',
  '/ai-agent-builders-hub': '/best-ai-agent-builder',

  // Comparison pages → compare routes
  '/cursor-vs-codex': '/compare/cursor-vs-codex',
  '/chatgpt-vs-perplexity': '/compare/chatgpt-vs-perplexity',
  '/crewai-vs-langgraph': '/compare/langgraph-vs-crewai',
  '/vapi-vs-retell': '/compare/vapi-vs-retell',
  '/copilot-vs-codex': '/compare/copilot-vs-codex',
  '/crewai-vs-autogen': '/compare/crewai-vs-autogen',
  '/cursor-vs-github-copilot': '/compare/cursor-vs-copilot',
  '/github-copilot-vs-cursor': '/compare/cursor-vs-copilot',
  '/dify-vs-flowise': '/compare/flowise-vs-dify',
  '/retell-vs-elevenlabs': '/compare/retell-ai-vs-elevenlabs',
  '/vapi-vs-synthflow': '/compare/vapi-vs-synthflow',
  '/claude-code-vs-codex': '/compare/claude-code-vs-codex',
  '/github-copilot-vs-tabnine': '/compare/github-copilot-vs-tabnine',
  '/github-copilot-vs-amazon-codewhisperer': '/compare/github-copilot-vs-amazon-codewhisperer',
  '/intercom-vs-freshdesk': '/compare/intercom-vs-freshdesk',

  // AI agent type/content pages → hub pages
  '/what-is-mcp': '/mcp-directory',
  '/ai-agent-benchmarks': '/rankings',
  '/ai-agent-benchmark': '/rankings',
  '/ai-agent-market-map': '/sitemap',
  '/ai-agent-security': '/ai-agents-for-security',
  '/ai-agent-news': '/sitemap',
  '/ai-agent-updates': '/sitemap',
  '/ai-agent-trends': '/sitemap',
  '/ai-agent-research': '/research',
  '/ai-agent-awards': '/rankings',
  '/ai-agent-awards-2026': '/rankings',
  '/ai-agent-statistics': '/rankings',
  '/ai-agent-scoring-system': '/methodology',
  '/ai-agent-glossary': '/sitemap',
  '/ai-agent-cases-and-examples': '/sitemap',
  '/ai-agent-roadmap': '/sitemap',
  '/ai-agent-examples': '/sitemap',
  '/ai-agent-pricing-india': '/pricing',
  '/ai-agent-adoption-report': '/research',
  '/ai-agent-tools': '/best-ai-agent-frameworks',
  '/ai-coding-agents': '/categories/coding-agents',
  '/ai-code-completion-tools': '/categories/coding-agents',
  '/hindi-ai-agent': '/india',
  '/dpdp-act-ai-compliance': '/compliance/dpdp-act-ai-agents',
  '/voice-ai-case-studies': '/best-ai-voice-agent',
  '/voice-ai-faq': '/best-ai-voice-agent',
  '/voice-ai-for-banking': '/best-ai-agent-for-call-centers',
  '/voice-ai-for-education': '/best-ai-agent-for-education',
  '/voice-ai-for-real-estate': '/best-ai-agent-for-real-estate-calls',
  '/vector-dbs': '/sitemap',
  '/what-is-rag': '/sitemap',
  '/what-is-tool-use': '/sitemap',
  '/what-is-agentops': '/agents/agentops',
  '/buyers-guides': '/best-ai-agent',
  '/alternatives': '/compare',
  '/business': '/categories/business',
  '/team': '/about',
  '/entity': '/sitemap',
  '/reviews': '/sitemap',
  '/industry-report': '/research',

  // Reddit review pages → agent pages
  '/vapi-reddit-review': '/agents/vapi',
  '/claude-code-reddit-review': '/agents/claude-code',
  '/retell-reddit-review': '/agents/retell-ai',
  '/best-ai-coding-agent-reddit': '/best-ai-agent-for-coding',
  '/best-ai-agent-builder-reddit': '/best-ai-agent-builder',
  '/best-ai-agent-course-reddit': '/best-ai-agent-course',

  // Entity/cost-calculator pages → agent pages
  '/cursor-ai': '/agents/cursor',
  '/cursor-ai-entity': '/agents/cursor',
  '/vapi-cost-calculator': '/agents/vapi',
  '/retell-cost-calculator': '/agents/retell-ai',

  // Tools redirects (remaining)
  '/tools/github-copilot': '/agents/github-copilot',
  '/tools/intercom-ai': '/agents/intercom-ai',

  // MCP related redirects
  '/mcp-security': '/mcp-directory',
  '/mcp-monitoring': '/mcp-directory',
  '/mcp-testing': '/mcp-directory',
  '/mcp-vscode-extension': '/mcp-directory',
  '/mcp-use-case-education': '/mcp-directory',
  '/mcp-open-source-projects': '/mcp-directory',
  '/building-custom-mcp-server': '/mcp-directory',

  // Trailing slash variants of pillar pages. Self-referential trailing-slash
  // variants (e.g. '/best-ai-voice-agent/' → '/best-ai-voice-agent') are
  // intentionally omitted: path normalization already canonicalizes them to
  // their slashless canonical route, so a redirect entry would never fire.
  '/what-is-mcp/': '/mcp-directory',
  '/best-ai-agents': '/best-ai-agent',
  '/best-ai-agents/': '/best-ai-agent',
  '/coding-agents-hub/': '/categories/coding-agents',

  // www prefix variant
  '/www.bestaiagent.in': '/',
};
